### ISSUE TITLE
Cadvisor change exposed port

### ISSUE THREAD

**Issue by kkalugerov** [stefanprodan/dockprom#104]
Is it possible to change the port of cadvisor, because when i try to change like this`ports: "8089:8089"` it in `docker-compose.exportets.yml` which serve for remote monitoring it seems to have no effect.. It always search for 8080/tcp but on my host this port is already in use.
Thanks in advance.

**Comment by stefanprodan** [comment]
Yes you can set the port using this flag https://github.com/prometheus/node_exporter/blob/master/node_exporter.go#L73

**Comment by kkalugerov** [comment]
@stefanprodan I'm talking about Cadvisor not about node_exporter , what you are showing me is flag for node_exporter port not for cadvisor.

**Comment by stefanprodan** [comment]
Ah sorry here is the cadvisor flag https://github.com/google/cadvisor/blob/master/cadvisor.go#L42

**Comment by kkalugerov** [comment]
How exactly should I pass it :?  In compose file as `command` or :?

**Comment by kkalugerov** [comment]
It works. Thank you @stefanprodan :)

**Comment by kkalugerov** [comment]
If I change remote cadvisor port should I change it also in the host cadvisor :?

**Comment by nightah** [comment]
@kkalugerov if you change the cadvisor port you need to change the job in:.

https://github.com/stefanprodan/dockprom/blob/0c9df3423d6be67a13f7dc6e7e23be434585d958/prometheus/prometheus.yml#L24

This should be updated to reflect whatever port you have changed to.

**Comment by kkalugerov** [comment]
> @kkalugerov if you change the cadvisor port you need to change the job in:.
> 
> [dockprom/prometheus/prometheus.yml](https://github.com/stefanprodan/dockprom/blob/0c9df3423d6be67a13f7dc6e7e23be434585d958/prometheus/prometheus.yml#L24)
> 
> Line 24 in [0c9df34](/stefanprodan/dockprom/commit/0c9df3423d6be67a13f7dc6e7e23be434585d958)
>  - targets: ['cadvisor:8080'] 
> 
> This should be updated to reflect whatever port you have changed to.

Thank you @nightah :)

**Comment by patrickjeried** [comment]
Hi @kkalugerov. im trying to change default port of cadvisor but it is not working. here's my docker-compose for cadvisor :

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    # ports:
    #   - 8000:8080
    command:
      - '-port=8098'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

and here's my prometheus.yml

scrape_configs:
    - job_name: prometheus
      scrape_interval: 5s
      static_configs:
      - targets:
        - prometheus:9090
        - cadvisor:8080
    - job_name: docker
      scrape_interval: 5s
      static_configs:
      - targets:
        - docker.for.mac.host.internal:9323

**Comment by patrickjeried** [comment]
Hi @kkalugerov. im trying to change default port of cadvisor but it is not working. here's my compose and prometheus.yml 
!clickme[docker-compose&prometheus.yml](https://pastebin.com/uu3JEfLq)
