### ISSUE TITLE
Monitor specific docker containers not all on the host.

### ISSUE THREAD

**Issue by kkalugerov** [stefanprodan/dockprom#107]
@stefanprodan Is there a way to observe particular docker containers not all of them which are ran on host ?

**Comment by thomasleveil** [comment]
You can achieve this using a Grafana dashboard variable:

- Go to the "Docker Containers" dashboard settings
- Add a new variable and configure it as follow: 
![image](https://user-images.githubusercontent.com/42300/48510454-3f32f080-e854-11e8-9dc7-e74fff70206b.png)
- Then edit graphs you want to apply the filter on to make them filter the containers on their name: 
![image](https://user-images.githubusercontent.com/42300/48510537-6d183500-e854-11e8-9da2-ffc135542884.png)

You now have a filter box at the top of your dashboard which accepts a regular expression to filter the containers on their name

![image](https://user-images.githubusercontent.com/42300/48510621-aea8e000-e854-11e8-9cc8-887ed9caa31c.png)

**Comment by nightah** [comment]
Thanks @thomasleveil.
@kkalugerov has this helped you, can we close off this issue?
