### ISSUE TITLE
Error rising when trying to set prometheus heap memory size..

### ISSUE THREAD

**Issue by kkalugerov** [stefanprodan/dockprom#109]
The problem is that when I set this property `--storage.local.target-heap-size=1073741824` in `docker-compose.yml` in prometheus section and when I run the docker-compose is throws me this exception from prometheus : `Error parsing commandline arguments: unknown long flag '--storage.local.target-heap-size'`
`prometheus: error: unknown long flag '--storage.local.target-heap-size'` .

@stefanprodan  Do you have any resolution for this problem mate ?

**Comment by stefanprodan** [comment]
There is no target-heap-size flag in Prometheus v2, this flag was for v1

**Comment by kkalugerov** [comment]
So is there a way to configure this or the process by itself takes what it needs ?
If so it will be good idea to update README.md :)

**Comment by kkalugerov** [comment]
Also I would like to ask is there a way to change prometheus admin passowrd ?

**Comment by stefanprodan** [comment]
you can set the user/pass via env vars
