### ISSUE TITLE
https proxy set for slack in alertmanager

### ISSUE THREAD

**Issue by 21kushagra** [stefanprodan/dockprom#111]
Hi,
How can I set up https_proxy url in order to send alerts using slack via https proxy?

I have tried to set in /etc/profile but still, the alertmanager is not using https proxy url.

Is there a way to set https proxy specific for alertmanager?

Best Regards

**Comment by nightah** [comment]
@21kushagra I'm not quite clear on exactly what you are trying to do.

Do you want to reverse proxy your instance so you can secure it with HTTPS?
If so, there's a couple different ways to do this some of which has been discussed here: https://github.com/stefanprodan/dockprom/issues/81.

If you are asking what the `url` setting for configuring a Slack alert in Grafana should be you should read https://api.slack.com/incoming-webhooks and http://docs.grafana.org/alerting/notifications/.
Both of these go through the appropriate detail on how to set this up.
