### ISSUE TITLE
what is the meaning of '{}' in volumes

### ISSUE THREAD

**Issue by chengsu** [stefanprodan/dockprom#114]
in **docker-compose.yml** file, there is:
```
volumes:
    prometheus_data: {}
    grafana_data: {}
```
What is the meaning of '{}' , any reference?
I just wonder where the data stores and how can i clean up.

**Comment by nightah** [comment]
@chengsu, the reference above is correct in regards to the volume.

Grafana's volume stores sessions and I just double checked mine and it's still under 1MB.

Prometheus' volume stores the actual chunked data, I have my retention set significantly higher than the default `200h`, it's set to `5y` with a little over 2 years worth of data and it's the following size: `29.8G`.

To clean up your data the best bet would be to adjust the following line for Prometheus:
https://github.com/stefanprodan/dockprom/blob/8ea5ce71670b35d78eda4ebff629074f7f97c32b/docker-compose.yml#L24
