### ISSUE TITLE
Updating releases

### ISSUE THREAD

**Issue by pascalandy** [stefanprodan/dockprom#116]
Curious to know if you are planning to keep them updated in the future. That would help the community to have a checkpoint in order to test the evolution of the project. 

Especially true since people are starting to follow `releases`.

![screen shot 2018-12-03 at 12 50 32 am](https://user-images.githubusercontent.com/6694151/49355426-8bc05d80-f695-11e8-8d66-ab8f97404a92.jpg)

Thank you!

**Comment by nightah** [comment]
We could likely do this, just need to figure out how we would want to order our releases.
Because it's obviously several different pieces of software put together.

@stefanprodan maybe we do independent release numbering specific to `dockprom` and increment minor releases for any minor release across any of the stack and major for any major releases, thoughts?

**Comment by stefanprodan** [comment]
Yes we could have dockprom releases independent from Prometheus or any other component. I would bump the major version every this there is a breaking change in one of the components or in compose. If for example Grafana v6 will be backwards compatible with v5 we should bump the minor version and so on. 

@nightah do you think we should delete the current releases and start from `v1.0.0` ?

**Comment by nightah** [comment]
@stefanprodan it probably makes sense to start from `v1.0.0` if we want to go down this path.

**Comment by stefanprodan** [comment]
I've retagged the old releases and made a 2.1.0 release just now.

**Comment by nightah** [comment]
I'll continue to increment as we make changes to the respective software too.
Thanks for the report @pascalandy.

**Comment by stefanprodan** [comment]
@nightah thanks so much for all the help, I really appreciate it 🤗

**Comment by stefanprodan** [comment]
@nightah now that I've deleted the old tags you should run `git pull --prune --tags` so they don't get pushed back when you commit to master.

**Comment by nightah** [comment]
Yep all good to go here, thanks :).

**Comment by pascalandy** [comment]
Thank you very much guys!
P.S. I see no button to close the issue. Weird

**Comment by pascalandy** [comment]
May I request a similar setup over https://github.com/stefanprodan/swarmprom/releases? It's the one aI use actually :)
