### ISSUE TITLE
Grafana has failed to load its application files during LOGIN

### ISSUE THREAD

**Issue by tonanuvem** [stefanprodan/dockprom#119]
After running "docker-compose up" and start to open http://IP:3000, Grafana does not load.

Error message, after waiting a while:

> If you're seeing this Grafana has failed to load its application files 
> 
> 1. This could be caused by your reverse proxy settings.
> 
> 2. If you host grafana under subpath make sure your grafana.ini root_path setting includes subpath
> 
> 3. If you have a local dev build make sure you build frontend using: npm run dev, npm run watch, or npm run build
> 
> 4. Sometimes restarting grafana-server can help

**Comment by nightah** [comment]
Can you paste the output of your Grafana logs `docker log grafana` please?
Are you hosting this behind a reverse proxy or bare defaults?
Have you tried restarting Grafana?

**Comment by tonanuvem** [comment]
The same Grafana error is happening with : stefanprodan/swarmprom

**Comment by nightah** [comment]
This looks to be an issue with `https://labs.play-with-docker.com` and how it reverse proxies to the backend Grafana service.

I haven't really had too much of a chance to look deeper in to this, but it might be the case that it's not something that we will even be able to fix. This definitely works when deploying on cloud services like AWS, Azure, GCP and of course your own PC/Server.

**Comment by nightah** [comment]
I'm not entirely sure if there's some sort of rate-limiting or something on their reverse proxy.

Unfortunately this isn't a dockprom or Grafana issue specifically. I suggest you lodge an upstream ticket for `play-with-docker`.

**Comment by marcosnils** [comment]
@nightah play-with-docker author here. PWD is using a custom reverse proxy indeed to forward traffic to the underlying container given the supplied URL. What I don't understand is why grafana needs some special configuration to work behind reverse proxies. I've checked the documentation but besides setting the server domain url config parameter I don't see anything else that we can configure. 

Can you help me understand what's grafana doing behind the scenes that affects this?. I don't see any errors neither in the browser nor the application logs.

**Comment by nightah** [comment]
@marcosnils what reverse proxy are you using for play-with-docker?

I've tried playing with Grafana and setting the server domain too but it doesn't resolve the issue.

**Comment by marcosnils** [comment]
@nightah it's fixed already. One of our firewall rules was preventing grafana assets to download propertly.

**Comment by xtremedata** [comment]
Hi,
I have the same result when login after installing https://dl.grafana.com/oss/release/grafana-5.4.2-1.x86_64.rpm on CentOS7 on AWS.

Would this log line be an indication of a problem: 
t=2019-03-20T18:30:47+0000 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers error="open /etc/grafana/provisioning/notifiers: no such file or directory"


Logs:
t=2019-03-20T18:30:47+0000 lvl=info msg="Starting Grafana" logger=server version=6.0.2 commit=3f4c2e7 branch=HEAD compiled=2019-03-19T13:06:06+0000
t=2019-03-20T18:30:47+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2019-03-20T18:30:47+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2019-03-20T18:30:47+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2019-03-20T18:30:47+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2019-03-20T18:30:47+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2019-03-20T18:30:47+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2019-03-20T18:30:47+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2019-03-20T18:30:47+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2019-03-20T18:30:47+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2019-03-20T18:30:47+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2019-03-20T18:30:47+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2019-03-20T18:30:47+0000 lvl=info msg="App mode production" logger=settings
t=2019-03-20T18:30:47+0000 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=11983
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing HTTPServer" logger=server
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing SqlStore" logger=server
t=2019-03-20T18:30:47+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2019-03-20T18:30:47+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing InternalMetricsService" logger=server
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing SearchService" logger=server
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing PluginManager" logger=server
t=2019-03-20T18:30:47+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing RenderingService" logger=server
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing AlertingService" logger=server
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing DatasourceCacheService" logger=server
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing HooksService" logger=server
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing LoginService" logger=server
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing QuotaService" logger=server
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing ServerLockService" logger=server
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing UsageStatsService" logger=server
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing UserAuthTokenService" logger=server
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing CleanUpService" logger=server
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing NotificationService" logger=server
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing ProvisioningService" logger=server
t=2019-03-20T18:30:47+0000 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers error="open /etc/grafana/provisioning/notifiers: no such file or directory"
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing TracingService" logger=server
t=2019-03-20T18:30:47+0000 lvl=info msg="Initializing Stream Manager"
t=2019-03-20T18:30:47+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=

**Comment by yonglezhu** [comment]
I just download grafana-7.3.5.linux-amd64.tar.gz，then
tar xf grafana-7.3.5.linux-amd64.tar.gz
cd grafana-7.3.5
./bin/grafana-server web

then vist http://ip:3000/ ，I see the same error message.I didn't modify the config file ,nor use any reserve proxy either
