### ISSUE TITLE
[Issue] can't change the password in user.config 

### ISSUE THREAD

**Issue by JeromeVi** [stefanprodan/dockprom#12]
Hi,
I want to change the password "changeme" by something like "admin" for example, so I did this in the config file:

```
GF_SECURITY_ADMIN_USER=admin
GF_SECURITY_ADMIN_PASSWORD=admin
GF_USERS_ALLOW_SIGN_UP=false

```

Then I do a` docker-compose up -d`

And when I go to "localhost:3000" I can only login with "changeme" (I tried with private navigator)

**Comment by stefanprodan** [comment]
Try removing the grafana container and volume than run compose up

**Comment by JeromeVi** [comment]
Already did it and nothing has changed @stefanprodan I have deleted the Grafana images + containers and made the compose up again but the same problem is still happening

**Comment by stefanprodan** [comment]
Have you removed the `grafana_data` volume? removing the container doesn't delete the volume

**Comment by JeromeVi** [comment]
You are right !
