### ISSUE TITLE
Prometheus filter contianer using wildcard 

### ISSUE THREAD

**Issue by sohel2020** [stefanprodan/dockprom#120]
https://github.com/stefanprodan/dockprom/blob/master/prometheus/alert.rules#L45
Let say in a single server I have 2 jenkins container named jenkins-kjfkfj7f and jenkins-5jkdjd

so how can I write a single alert rule for this two container? and sent right container name with alert description.

**Comment by nightah** [comment]
I don't believe you can do that with the [absent](https://prometheus.io/docs/prometheus/latest/querying/functions/#absent) query function, the moment you try to add multiple containers in a query the last `name` or tag takes precedence.

I can see you have already posted this upstream in the prometheus repo, there might be some other smarter way to do this but I believe to determine a container being `down` you need a separate rule.
