### ISSUE TITLE
Slack notification points to incorrect url

### ISSUE THREAD

**Issue by mebibou** [stefanprodan/dockprom#124]
When I receive a notification on slack, the url points to something like `http://988e9a61afe2:9093/#/alerts?receiver=slack`. I'm not sure what this `988e9a61afe2` is, but how to configure the url? is it in the configuration files of this repo? I couldn't find it

**Comment by satshabad-cr** [comment]
Seems like the nodename of the container rather than the ip of the actual host

**Comment by nightah** [comment]
`988e9a61afe2` is the random generated hostname for your container.
The instructions @pagm has given you is what you need to do, you should be setting up the `--web.external-url` for both alertmanager and prometheus for consistent behaviour :).
