### ISSUE TITLE
unable to insert jump to DOCKER-ISOLATION-STAGE-1 rule in FORWARD chain

### ISSUE THREAD

**Issue by Rahimianes** [stefanprodan/dockprom#130]
Hi
i have a problem with installation 
when i run this command : 
ADMIN_USER=admin ADMIN_PASSWORD=newpass docker-compose up -d

i see this error: 
Creating network "dockprom_monitor-net" with driver "bridge"
ERROR: unable to insert jump to DOCKER-ISOLATION-STAGE-1 rule in FORWARD chain:  (iptables failed: iptables --wait -I FORWARD -j DOCKER-ISOLATION-STAGE-1: iptables v1.6.0: Couldn't load target `DOCKER-ISOLATION-STAGE-1':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2))

how can i solve this problem ?
thanks

**Comment by Jagostini** [comment]
Hello
I had the same problem
Check the configuration of your firewall, you may have forgotten the configuration of the docker.

Example with shorewall
```
/etc/shorewall/shorewall.conf:

DOCKER=Yes
/etc/shorewall/zones:

#ZONE         TYPE        OPTIONS
dock          ipv4        #'dock' is just an example -- call it anything you like
/etc/shorewall/policy:

#SOURCE        DEST        POLICY         LEVEL
dock           $FW         REJECT
dock           all         ACCEPT
/etc/shorewall/interfaces:

#ZONE          INTERFACE        OPTIONS
dock           docker0          bridge   #Allow ICC (bridge implies routeback=1)
or

#ZONE          INTERFACE        OPTIONS
dock           docker0          bridge,routeback=0   #Disallow ICC
```

**Comment by Rahimianes** [comment]
Hi
i am using csf firewall that integrated with Iptables 
how can i resolve the problem with iptables ?
thanks

**Comment by nightah** [comment]
@Rahimianes typically the IPTABLES rules are created by installing the Docker package with your distro.
If these have not been created I would be looking at either the Docker package or your upstream with your firewall of choice.

**Comment by diepes** [comment]
?

**Comment by trueshanti** [comment]
> Where is the required rules documented ?

did you get a clue on this ?
