### ISSUE TITLE
Avoid using the port 3000

### ISSUE THREAD

**Issue by zedtux** [stefanprodan/dockprom#133]
The 3000 port is the default port for Rails projects, so it is conflicting with Grafana's one from this project.

Could you please use another port instead?

**Comment by nightah** [comment]
You can remap the port to whatever you want with Docker, just change the left side of https://github.com/stefanprodan/dockprom/blob/388f1b3f957045f28d51abe898cd63bf63889ab4/docker-compose.yml#L125 with your desired port.

**Comment by zedtux** [comment]
Thank you @nightah I figured it out.
