### ISSUE TITLE
Data Rentention

### ISSUE THREAD

**Issue by gmoler** [stefanprodan/dockprom#134]
Container has been up since 3/7/19, after this past weekend i logged in and it only has logging data back to 3/26

Is there a setting for default data retention that could be affecting this?

**Comment by gmoler** [comment]
I am seeing a 15d retention as default, however the math doesnt appear to be working that, i have two completely independent systems that both have their earliest entry at 3/26 22:00, very weird

**Comment by nightah** [comment]
@gmoler you can adjust the default retention in your main `docker-compose.yml`
https://github.com/stefanprodan/dockprom/blob/aaef88ae801be4f8d87f48b8d554cf2725188652/docker-compose.yml#L24

Default is set to `200h` (hours) you can adjust this to be `1m` (month), `1y` (year) or whatever you prefer.
