### ISSUE TITLE
nodeexporter is running privileged

### ISSUE THREAD

**Issue by hacker-h** [stefanprodan/dockprom#137]
Is it really required to run the nodeexporter privileged?
It would make sense to identify the required capabilities and grant them explicitly:
https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

**Comment by nightah** [comment]
I'm actually not entirely certain the reason behind this, @stefanprodan does this happen to remind you of anything?

I can only trace the privileged flag back to the following issue: https://github.com/stefanprodan/dockprom/issues/29 which seems to suggest that running node-exporter without the privileged flag will not work. Though with my testing this doesn't appear to be the case, also I'm fairly certain we can drop the root user specification on the container too.

I'll run some more tests on a couple more instances and if I don't see any issues I'll commit back a fix to drop privileges and the root user.
