### ISSUE TITLE
Caddy error

### ISSUE THREAD

**Issue by Nexyll** [stefanprodan/dockprom#138]
Hello,

I deployed the stack following these instructions
```
git clone https://github.com/stefanprodan/dockprom
cd dockprom
ADMIN_USER=admin ADMIN_PASSWORD=admin docker-compose up -d
```
But when i try to access grafana on port 3000 with the docker host ip, caddy container logs give me this error :
```
Activating privacy features... done.
http://:9090
http://:9093
http://:9091
http://:3000
17/Apr/2019:11:35:18 +0000 [ERROR 502 /] context canceled
```
Do you have an idea of what may have gone wrong? because I've don't changed anything in the docker-compose file...

**Comment by ravvereddy** [comment]
Please check the datasource is present inside the grafana container or not.
Check your prometheus is up and running without any restarts.

**Comment by nightah** [comment]
@Nexyll can you provide the logs for both your Grafana and Prometheus containers too please?

**Comment by nightah** [comment]
@Nexyll I'm closing this off due to lack of activity, if you're still experiencing issues please ask for this to be reopened with the appropriate details requested above or lodge a new issue.
