### ISSUE TITLE
Grafana - Import Dashboard while build

### ISSUE THREAD

**Issue by DirkNachbar** [stefanprodan/dockprom#139]
Hi Stefan,

first at all, your dockprom is really cool !

I am using your dockprom solution here in a project and we have created several own Dashboards in Grafana. 
Now we want to export our own dashboards and place them in the directory grafana/dashboards, so that these dashboards should be installed during the build process of a docker environment.

Unfortunatelly the export format is not the same as the required import format:

[{"fieldNames":["Dashboard"],"classification":"RequiredError","message":"Required"}]

So my question is, how did you export your dashboard json files in the grafana/dashboards folder? Any special trick? I have tried several options for the export, but none of them provides the correct format for the import.

Thanks in advanced.

Cheers
Dirk

**Comment by a4sh3u** [comment]
I'm also facing a similar situation. If I use the db endpoint (**/api/dashboards/db**), then I get the below error 

> \* We are completely uploaded and fine
> \* The requested URL returned error: 422 Unprocessable Entity
> \* Curl_http_done: called premature == 1
> \* stopped the pause stream!
> 100 94002    0     0  100 94002      0  4204k --:--:-- --:--:-- --:--:-- 4371k
> \* Closing connection 0
> curl: (22) The requested URL returned error: 422 Unprocessable Entity
> install failed

And using the import endpoint (**/api/dashboards/import**), which is not recommended method, my dashboards are installed, but I still get some errors as shown below

> \* We are completely uploaded and fine
> \* The requested URL returned error: 500 Internal Server Error
> \* Curl_http_done: called premature == 1
> \* stopped the pause stream!
> t=2019-04-26T14:56:22+0000 lvl=eror msg="Request error" logger=context userId=1 orgId=1 uname=admin error="runtime error: invalid memory address or nil pointer dereference" stack="/usr/local/go/src/runtime/panic.go:513 (0x435098)\n/usr/local/go/src/runtime/panic.go:82

**Comment by nightah** [comment]
@DirkNachbar assuming that your dashboard file is called `dashboard.json` perform the following command while in the directory that holds the file, this will generate `dashboard.new.json` that you can use for provisioning:

```
echo "{\"dashboard\": `cat dashboard.json`}" > "dashboard.new.json"
```

This is effectively adding the following to the beginning and end of the json file:
`{"dashboard":`
`}`

You can see exactly what was done as part of this commit: https://github.com/stefanprodan/dockprom/commit/52e11173c4f664696d00f0674714e57684245f90
