### ISSUE TITLE
Monitoring multiple remote hosts

### ISSUE THREAD

**Issue by rudasn** [stefanprodan/dockprom#140]
Hey. Thanks for sharing this tool, I appreciate the effort.

I was wondering if it's possible to use it to monitor multiple remote hosts, instead of the system it runs on.

The monitoring services (eg. cadvisor) would run on each host and send data to a remote storage host (running prometheus and grafana).

Thanks for your time.

**Comment by m-peko** [comment]
Hi there,
It is possible.
You need to run `docker-compose.exporters.yml` on each of the remote hosts. This will install `node-exporter` (for host monitoring) and `cadvisor` (for container monitoring) only.
Then, on the system that runs `grafana` and everything else, update `prometheus.yml` configuration file with your remote hosts as targets.

Thanks and regards,
Marin

**Comment by rudasn** [comment]
@m-peko Hey, thanks for the help. 

Is it possible for `node-exporter` and `cadvisor` to push their stats to the host that runs `grafana`, instead of pulling from each host?

The reason I'm asking is because each host is behind a (different) VPN and it's not possible (AFAIK) for the `grafana`/`prometheus` server to connect to each host programmatically to gather stats.

Thanks again!

**Comment by m-peko** [comment]
I think it's not possible to push stats in a formal way but you can make a workaround as shown [here](https://github.com/prometheus/node_exporter/issues/279).

Thanks and regards,
Marin

**Comment by m-peko** [comment]
@rudasn Have you managed to solve your problem?

**Comment by rudasn** [comment]
@m-peko It looks like the only "suggested" way to do this is by using a cron job on each node to collect and push the metrics. I haven't tried it yet but it sounds pretty straight forward.

Thanks for your help

**Comment by nightah** [comment]
Thanks for the assistance on this one in my absence @m-peko, @rudasn if you have any other questions please don't hesitate to open another issue.
