### ISSUE TITLE
cadvisor and nodeexporter errors on startup

### ISSUE THREAD

**Issue by petrjahoda** [stefanprodan/dockprom#141]
While trying to run on Windows 10, two containers do not start with this error:
ERROR: for cadvisor  Cannot create container for service cadvisor: invalid volume specification: '/host_mnt/rootfs:ro'

ERROR: for nodeexporter  Cannot create container for service nodeexporter: invalid volume specification: '/host_mnt/rootfs:ro'

**Comment by GosthMan** [comment]
Hello
That error is because the mount point is incorrect.
Please correct it and it will work.
If your server folder is /host_mnt then your mount should be 
- /host_mnt/:/rootfs:ro

**Comment by spex66** [comment]
Warning: I'm still a Docker noob :)

@petrjahoda: just to be sure, you have tried to start on Windows 10 host but using Linux containers, is this correct?

I've tried to `docker-compose up -d` on Windows Server 2019 *and Windows containers*, and run into:
```
>docker-compose up -d
Creating network "dockprom_monitor-net" with driver "bridge"
ERROR: could not find plugin bridge in v1 plugin registry: plugin not found
```

Which seems to be an unresolved issue so far:
* https://github.com/docker/for-win/issues/1960

As there are no `plugin` support on Windows yet:
```
>docker plugin ls
Error response from daemon: plugins are not supported on this platform
```

Can someone confirm, that `dockprom` stack is not supposed to run on Windows containers, to monitor Windows host and docker container?

thx
Peter
(=PA=)

**Comment by spex66** [comment]
Scratch my question, I've realized that `dockprom` stack can only run on Linux containers for now.
i.e.: missing cAdvisor support for Windows: https://github.com/google/cadvisor/issues/2170

I'm happy to have found `dockprom` for my Linux based Docker-projects, it is simply awesome.
And you cannot have it all :)
(=PA=)

**Comment by nightah** [comment]
So to the best of my knowledge dockprom has only been tested on Linux extensively and Mac OSX.
Some of the upstream dependencies don't support Windows as of yet therefore we cannot support them either.

**Comment by Dovry** [comment]
FYI if you comment out 
```
- /:/rootfs:ro
```
on both cAdvisor and node-exporter you can start the stack. You'll barely get any CPU/Network metrics, but it's better than nothing.
![image](https://user-images.githubusercontent.com/15201298/62797996-809fb600-badd-11e9-950c-01ce4b4cd7bc.png)


![image](https://user-images.githubusercontent.com/15201298/62798061-a2993880-badd-11e9-911f-a5d031dc3f4a.png)


![image](https://user-images.githubusercontent.com/15201298/62798109-c5c3e800-badd-11e9-8502-7f3622a903cf.png)
