### ISSUE TITLE
Suggestion: use https://renovatebot.com/ to update versions

### ISSUE THREAD

**Issue by pascalandy** [stefanprodan/dockprom#142]
Cheers!

**Comment by nightah** [comment]
That would be all good and well, but the key thing is ensuring that when updating the depdencies that it's tested so none of the existing featureset breaks.

I'll have a look in to this further but unless it provides some sort of testing capability too this is probably unlikely.

**Comment by stefanprodan** [comment]
Blindly updating versions would just break the project. To make this work, renovatebot should create PRs and with CircleCI or some other free CI run integration tests. Writing integration tests that check each graph in our dashboards is a lot of work.
