### ISSUE TITLE
Error loading prometheus.yml

### ISSUE THREAD

**Issue by ajithkrishnar** [stefanprodan/dockprom#143]
prometheus      | level=error ts=2019-06-06T17:17:22.649Z caller=main.go:717 err="error loading config from \"/etc/prometheus/prometheus.yml\": couldn't load configuration (--config.file=\"/etc/prometheus/prometheus.yml\"): open /etc/prometheus/prometheus.yml: permission denied"

i followed steps in #13 but still same issue .

its running in vm

**Comment by nightah** [comment]
@ajithkrishnar can you confirm the permissions in your `dockprom/prometheus` folder please?

**Comment by nightah** [comment]
@ajithkrishnar I'm closing this off due to inactivity, if you continue to experience this issue, please provide the details requested above and I'll re-open the issue.
