### ISSUE TITLE
Grafana 6 compatibility

### ISSUE THREAD

**Issue by perrefe** [stefanprodan/dockprom#145]
The json spec file doesn't work with Grafana 6.2.2, it produces a blank dashboard.

**Comment by nightah** [comment]
If you're trying to import the provided dashboard `.json` files you need to remove the following at the beginning and end of the json file:

`{"dashboard":`
`}`

They're provided in that format so they can be provisioned and created on first run.

See https://github.com/stefanprodan/dockprom/issues/139#issuecomment-487268291 for more info.
