### ISSUE TITLE
multiple datasources

### ISSUE THREAD

**Issue by EmaLinuxawy** [stefanprodan/dockprom#146]
how i can use it with multiple datasources

**Comment by EmaLinuxawy** [comment]
@nightah Thanks for your response.

actually i mean how i can use single dashboard for multiple datasources 
i do that by variables but no data changed between data sources

**Comment by nightah** [comment]
This has been discussed in depth over at #8 I would suggest you do some reading regarding Grafana templating.
Dockprom is catered towards a single stack, though there is nothing stopping you from adding in multiple data sources and modifying the Dashboards to cater for these with variables.
