### ISSUE TITLE
No Datapoints

### ISSUE THREAD

**Issue by lukebarton** [stefanprodan/dockprom#15]
Following the README to the letter, I get no datapoints in prometheus.
Three target's are "UP".
/graph on any basic metric reports "No Datapoints"
Grafana reports the datasource "is working".
Grafana Dashboard for "Docker Containers" is empty of data.

OSX, Docker for Mac 
Version 17.03.1-ce-mac5 (16048)
Channel: stable
b18e2a50cc

**Comment by lukebarton** [comment]
For anyone else who ends up here, restarting the Docker host resolved the issue. I believe it was related to a recent daylight-saving timezone change, based on my research.

**Comment by dmelo** [comment]
I had the same problem. Perhaps it is a good idea to include that on the README.md file.

**Comment by stefanprodan** [comment]
I've checked all production servers where I run this setup and none had this problem. I think it's a Docker for Mac problem, on Ubuntu Server 16.04 al works well.

**Comment by dmelo** [comment]
I'm using on Fedora 25

```dmelo@merov2:~$ docker version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:06:13 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:06:13 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by chrouzz** [comment]
I have the same issue, many of the data are not working. I am using linux amazon AMI. 
![image](https://cloud.githubusercontent.com/assets/5631944/25034248/9cc664ee-2117-11e7-8d1d-7a4ebe2c4947.png)

![image](https://cloud.githubusercontent.com/assets/5631944/25034272/a93a0a28-2117-11e7-8efa-0761ec0d78c7.png)

![image](https://cloud.githubusercontent.com/assets/5631944/25034281/b9594e5a-2117-11e7-9942-7ae829d27350.png)

only some data are working but 80% is not. Any idea?

**Comment by gonberdeal** [comment]
I think you can not launch cadvisor as a service in docker swarm (docker service create). Try launching cadvisor directly with "docker run"

**Comment by pascalandy** [comment]
On my side I tried the docker-compose on play-with-ghost without any issue.
Now running in prod on Ubuntu 16.04 hosts :)
