### ISSUE TITLE
grafana container permission denied

### ISSUE THREAD

**Issue by codeasashu** [stefanprodan/dockprom#151]
I am trying to bring up grafana container by doing

```sh
ADMIN_USER=admin ADMIN_PASSWORD=admin sudo docker-compose up grafana
```

where I get this error:

```
Creating network "dockprom_monitor-net" with driver "bridge"
Creating grafana ... error

ERROR: for grafana  Cannot start service grafana: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/setup.sh\": permission denied": unknown

ERROR: for grafana  Cannot start service grafana: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/setup.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.
```

git log -1: `327b4c57152ee44fd3f86a1e658a829bac9e6922`
can confirm I am using latest repo

**Comment by codeasashu** [comment]
I am sorry I didn't mentioned that I am using this inside minikube docker host. I forgot that my zshrc had `eval $(minikube docker-env)` setup. Unsettting it solved the issue

**Comment by jamshid** [comment]
I'm getting the same error in a non-minikube Docker 18.09.7 on Ubuntu 16.04 environment. 
Any idea what the problem might be? Something with user ids/file permissions?

**Comment by codeasashu** [comment]
@jamshid Can you try setting permission on `grafana/setup.sh` from your host machine? try with full permissions `sudo chmod 777 grafana/setup.sh` and then try bringing up the project?

**Comment by jamshid** [comment]
Doh... I forgot this docker-compose.yml and associated files need to be on the file system of the docker server itself ("Clone this repository on your Docker host..."). They rely on mapping the local file system to container volumes.
