### ISSUE TITLE
Change default port 3000?

### ISSUE THREAD

**Issue by gerroon** [stefanprodan/dockprom#152]
Hi

The port 3000 is taken in my system. How can I use another port properly with your setup?

Thanks

**Comment by letnab** [comment]
> Hi
> 
> The port 3000 is taken in my system. How can I use another port properly with your setup?
> 
> Thanks

hi! 
change `docker-compose.yml`

caddy:
    image: stefanprodan/caddy
    container_name: caddy
    ports:
      - "**80**:3000"# 80 your port  or another
      - "9090:9090"
      - "9093:9093"
      - "9091:9091"

**Comment by nightah** [comment]
@gerroon pretty much as per @letnab's comments, or you can look at some of the previous issues like: https://github.com/stefanprodan/dockprom/issues/133#issuecomment-477899012
