### ISSUE TITLE
Prometheus 2.12.0 panics?

### ISSUE THREAD

**Issue by logopk** [stefanprodan/dockprom#155]
Hi,

Updated to HEAD this morning:

level=info ts=2019-08-19T15:34:34.047Z caller=main.go:329 msg="Starting Prometheus" version="(version=2.12.0, branch=HEAD, revision=43acd0e2e93f9f70c49b2267efa0124f1e759e86)"
level=info ts=2019-08-19T15:34:34.048Z caller=main.go:330 build_context="(go=go1.12.8, user=root@7a9dbdbe0cc7, date=20190818-13:53:16)"
level=info ts=2019-08-19T15:34:34.049Z caller=main.go:331 host_details="(Linux 4.14.134-boot2docker #1 SMP Mon Jul 22 20:22:16 UTC 2019 x86_64 d63665af60aa (none))"
level=info ts=2019-08-19T15:34:34.049Z caller=main.go:332 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-08-19T15:34:34.049Z caller=main.go:333 vm_limits="(soft=unlimited, hard=unlimited)"
**panic: runtime error: slice bounds out of range**

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.parseBrokenJson(0xc0008db000, 0x4e21, 0x4e21, 0x2a6b7c0, 0xc00077a3f0, 0x0, 0x0, 0xc00028e1c0)
        /app/promql/query_logger.go:45 +0x131
github.com/prometheus/prometheus/promql.logUnfinishedQueries(0xc00028e1c0, 0x1a, 0x4e21, 0x2a6b7c0, 0xc00077a3f0)
        /app/promql/query_logger.go:70 +0x552
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7ffc471c3e7f, 0xb, 0x14, 0x2a6b7c0, 0xc00077a3f0, 0x2a6b7c0)
        /app/promql/query_logger.go:108 +0x131
main.main()
        /app/cmd/prometheus/main.go:361 +0x52bd

Is there any migration necessary between 2.11.1 and 2.12.0 .

Best regards.

Peter

**Comment by nightah** [comment]
Sorry for the delayed response, have been away on holidays.
I did not have any issues upgrading and no migration was necessary.

Looking on the Prometheus github it looks like people experiencing the same issue restarted without any issues, does the issue keep recurring after a restart?

**Comment by logopk** [comment]
still does :-(

**Comment by nightah** [comment]
I've tried this on a several different machines with different specs both, fresh installs and old and I cannot replicate the issue, I would suggest lodging an issue over at https://github.com/prometheus/prometheus/issues with all the detail requested to see if they might be able to help.
