### ISSUE TITLE
Installation fails - For pushgateway v0.9.1: no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by bahree** [stefanprodan/dockprom#159]
Hi,
I am trying to install dockprom on a raspberry pi, and after cloning the repo and running, I get the following error. It does pull a number of other images, but seems to be failing on this one.

```
pi@pi-server2:~/docker/dockprom $ sudo ADMIN_USER=admin ADMIN_PASSWORD=mypwd docker-compose up -d                                                    
Pulling pushgateway (prom/pushgateway:v0.9.1)...
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```
When I [search on the docker hub](https://hub.docker.com/search?q=prom%2Fpushgateway&type=image&architecture=) I do see a [linux arm v7 listed](https://hub.docker.com/r/prom/pushgateway-linux-armv7) - is there a typo in the docker compose yaml file? Any ideas?

Thanks.

**Comment by nightah** [comment]
It's not a typo, dockprom is intended and supported for amd64 architecture.

You're welcome to change the container it references to the pushgateway one for ARM, though I would probably suggest lodging an upstream issue asking them to create a proper docker manifest so the same container can be pulled by different architectures.
