### ISSUE TITLE
DockerFile

### ISSUE THREAD

**Issue by lakshmanvvs** [stefanprodan/dockprom#16]
Is there a Dockerfile for this repo or is it missing?

**Comment by unixhup** [comment]
Check the composerfile and get your dockerfiles directly from dockerhub. Stefanprodan havnt written own containers, just customized official ones.

**Comment by unixhup** [comment]
Customized is the wrong word, hes just using official containers from dockerhub without any changes in the dockerfiles

**Comment by lakshmanvvs** [comment]
Thank you. I'll close this issue.
