### ISSUE TITLE
Both options should work, I would create new jobs and use the job name to filter the dashboards in case you want to focus just on one host.

### ISSUE THREAD

**Issue by raysbudo** [stefanprodan/dockprom#160]
Both options should work, I would create new jobs and use the job name to filter the dashboards in case you want to focus just on one host.

_Originally posted by @stefanprodan in https://github.com/stefanprodan/dockprom/issues/4#issuecomment-258508436_

Stefan I have done what you suggested each host has its own job_name, what I am having trouble with is the correct promql to pull just the container metrics from the individual hosts. and present them as individual metrics for either a set of containers from the remote host or solo container

**Comment by nightah** [comment]
@raysbudo: is this still an issue?
If you have separate jobs for each host then your query just needs to specify that in the respective dashboard, an alternative could be to create a variable to query on which is based off the job name.

https://grafana.com/docs/reference/templating/ is what you probably want to read for this.

**Comment by nightah** [comment]
Closing this off if you still have issues please open a new ticket.
