### ISSUE TITLE
add description for snap users for cadvisor 

### ISSUE THREAD

**Issue by mspencerl87** [stefanprodan/dockprom#161]
When using defaults and docker-compose up
Snap users get the following

ERROR: for cadvisor  Cannot start service cadvisor: error while creating mount source path '/var/lib/docker': mkdir /var/lib/docker: read-only file system

Any idea what path should be used in docker-compose.yml?
/:rootfs:ro
/var/lib/docker:/var/lib/Docker - Doesn't exist with snap.

**Comment by nightah** [comment]
@mspencerl87 could you clarify what you mean by snap, what's that in reference to?

**Comment by mspencerl87** [comment]
sudo snap install docker.. 
I would just close this.
I tested this across two hosts, it seems to be a issue with the docker snap package itself and not this repository.. 
Trying to reach out to launchpad
