### ISSUE TITLE
Erro on execute docker-composer

### ISSUE THREAD

**Issue by luismaruccio** [stefanprodan/dockprom#162]
Canddy don't start

`ERROR: for caddy  Cannot start service caddy: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"read init-p: connection reset by peer\"": unknown`

**Comment by nightah** [comment]
@luismaruccio can you please provide the following information:
- Host OS
- Output of `docker version`
- Output of `docker info`
- Docker compose version

**Comment by nightah** [comment]
I'm going to assume that you've managed to work this out, if not please request for this to be re-opened with the aforementioned details.
