### ISSUE TITLE
TCP port 9093 is busy, how change port for AlertManager?

### ISSUE THREAD

**Issue by CSRedRat** [stefanprodan/dockprom#163]
Hi! I have installed AlertManager in GitLab Omnibus bundle and don't touch this.
How I can change custop TCP port for AlertManager in docker-compose and other configs?

And how I can install dockprom with Sourcegraph installation?

  caddy:
    image: stefanprodan/caddy
    container_name: caddy
    ports:
      - "3000:3000"
      - "9090:9090"
      - "9093:9093"

  alertmanager:
    image: prom/alertmanager:v0.19.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093

Digest: sha256:44541cfacb66f4799f81f17fcfb3cb757ccc8f327592745549f5930c42d115c9
Status: Downloaded newer image for stefanprodan/caddy:latest
Creating pushgateway ...
Creating nodeexporter ...
Creating cadvisor     ...
Creating alertmanager ...
Creating pushgateway  ... done
Creating nodeexporter ... done
Creating cadvisor     ... done
Creating alertmanager ... done
Creating prometheus   ... done
Creating grafana      ... done
already in use

ERROR: for caddy  Cannot start service caddy: driver failed programming external connectivity on endpoint caddy (d70a65f0612e1943d002faceeb63e30ad659f7b85f91c14d1f2aeddbca79c04a): Error starting userland proxy: listen tcp 0.0.0.0:9093: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by nightah** [comment]
You need to modify the left side of the colon `:` here:
https://github.com/stefanprodan/dockprom/blob/f6aec3bfaa7df4c14b8b09e712864dbabe86a94d/docker-compose.yml#L122

**Comment by olegsidokhmetov** [comment]
Hello!

I have almost the same problem, but with port 3000

```
 docker-compose restart
Restarting prometheus   ... done
Restarting alertmanager ... done
Restarting grafana      ... done
Restarting pushgateway  ... done
Restarting caddy        ... error
Restarting nodeexporter ... done
Restarting cadvisor     ... done

ERROR: for caddy  Cannot restart container aa1ead893db4ebd708bc16f10c9f9435756b54ad4f65bb5d9c919946be64c0f3: driver failed programming external connectivity on endpoint caddy (640bd562f2c7e2b74a53e14ea36051e33cb5df1429756ba47d1a96511f951164): Error starting userland proxy: listen tcp4 0.0.0.0:3000: bind: address already in use
```

```
lsof -i -P -n | grep
node        13643      rocketchat   25u  IPv4    47783      0t0  TCP *:3000 (LISTEN)
node        13643      rocketchat   41u  IPv4 12688985      0t0  TCP 127.0.0.1:3000->127.0.0.1:50172 (ESTABLISHED)
node        13643      rocketchat   44u  IPv4 12688996      0t0  TCP 127.0.0.1:3000->127.0.0.1:50178 (ESTABLISHED)
node        13643      rocketchat   47u  IPv4 12870386      0t0  TCP 127.0.0.1:3000->127.0.0.1:37204 (ESTABLISHED)
nginx      356029        www-data   22u  IPv4 12688984      0t0  TCP 127.0.0.1:50172->127.0.0.1:3000 (ESTABLISHED)
nginx      356029        www-data   23u  IPv4 12870385      0t0  TCP 127.0.0.1:37204->127.0.0.1:3000 (ESTABLISHED)
nginx      356029        www-data   25u  IPv4 12688995      0t0  TCP 127.0.0.1:50178->127.0.0.1:3000 (ESTABLISHED)
```

```
netstat -pna | grep 3000
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      13643/node
tcp        0      0 127.0.0.1:3000          127.0.0.1:37204         ESTABLISHED 13643/node
tcp        0      0 127.0.0.1:37204         127.0.0.1:3000          ESTABLISHED 356029/nginx: worke
tcp        0      0 127.0.0.1:3000          127.0.0.1:50178         ESTABLISHED 13643/node
tcp        0      0 127.0.0.1:3000          127.0.0.1:50172         ESTABLISHED 13643/node
tcp        0      0 127.0.0.1:50172         127.0.0.1:3000          ESTABLISHED 356029/nginx: worke
tcp        0      0 127.0.0.1:50178         127.0.0.1:3000          ESTABLISHED 356029/nginx: worke
```
How to change port Grafana?  And witch? And on which one better?

I tied to change to 
```
    expose:
      - "3000:3000"
```

But ger error
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.grafana.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
```
