### ISSUE TITLE
Question on Update to 3.2.0 version

### ISSUE THREAD

**Issue by logopk** [stefanprodan/dockprom#164]
Hi,
is this mentioned procedure

> Breaking Changes:
As we have transitioned to utilise the grafana provisioning system due to curl being removed from the base docker image, this means that on upgrade any changes you have made to the Prometheus data source, or any of the provided dashboards will be reverted to the original state.
> It is recommended that you export any dashboards which have been changed to a json file, then perform an upgrade and re-import said changes to ensure the appropriate data is presented.
> Alternatively you can replace the provided .json files in the grafana/provisioning/dashboards/ folder with your exported dashboards.

a onetime todo? or every update? if I have the dashboards on a docker volume will they also be killed?
Thanks for the help!

Peter

**Comment by nightah** [comment]
It's a one time, basically what happens is it utilises the json files provided in the `grafana/provisioning/dashboards/` for a one off and then if you change them via the ui those will stay until the local files are changed again (which we typically do not do).

If you replace the json files then basically it will appear as if nothing as changed for you.

**Comment by nightah** [comment]
@logopk does my above explanation help?

**Comment by logopk** [comment]
@nightah it worked - apparently things have changed quite a bit - my exported Nginx-Version will no longer work. but I'll diff it once I get home and have access to a better diff-tool.

**Comment by nightah** [comment]
Great if you have any questions or issues please don't hesitate to create a new issue.
