### ISSUE TITLE
MacOS vs AWS

### ISSUE THREAD

**Issue by thomasd3** [stefanprodan/dockprom#165]
When I run it on MacOS, everything works perfectly.
On a machine running CentOS, works perfectly too.

On AWS, on the other hand, there is absolutely no events being received from the docker socket.

Any idea why this could be happening?

**Comment by nightah** [comment]
Could you please be a little more specific as to which component appears to not be working in AWS?

**Comment by thomasd3** [comment]
We can close this one; it's not related to dockprom, however it may be good to keep it for the record: under CentOS, the Docker socket was normally accessible and it is possible to get the info from the containers running. With the CentOS / AWS image and the docker install which is not exactly the same apparently, I had to explicitly name the socket path in the docker config, otherwise it is not accessible.
