### ISSUE TITLE
docker-compose down fail

### ISSUE THREAD

**Issue by Blueswen** [stefanprodan/dockprom#166]
Hi, I tried to stop all service with docker-compose stop command

```
$ docker-compose down
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

I also tried with COMPOSE_HTTP_TIMEOUT=360, but still get the same error message

```
$ COMPOSE_HTTP_TIMEOUT=360 docker-compose down
```

Then I tried with --verbose as options

```
$ docker-compose --verbose down
# others log
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- ('b9b0ef22ac1f3bdd12a032ce2693470d9273bf15500b423a5a13d8838c6cb09b')
```

It seems stop when it try to inspect cadvisor container(container_id=b9b0ef22ac1f).

Is there any way to stop all service?

**Comment by JinnaBalu** [comment]
This issue is related to docker, no issue with prem containers. 

By simply restarting the docker service via 

> sudo service docker restart

 I was able to get the aforementioned error to go away when running 

> docker-compose down

> docker-compose up 

> docker volume rm $(docker volume ls -f dangling=true -q) - Optional

**Comment by nightah** [comment]
@Blueswen is this issue still persistent?

**Comment by Blueswen** [comment]
It’s solved after docker restart. Thanks a lot!
