### ISSUE TITLE
volume add /etc/grafana/config to edit grafana.ini

### ISSUE THREAD

**Issue by mspencerl87** [stefanprodan/dockprom#168]
Can you add a folder in /grafana/config to so grafana.ini can be edited?
or is there a way to add this with Environment Variable?
Trying to make a dashboard public (No password)
Tried adding
GF_AUTH_PROXY_AUTO_SIGN_UP=false
GF_AUTH_PROXY_ENABLED=true
But it didn't work.

**Comment by nightah** [comment]
The environment variables you can modify for Grafana are documented [here](https://grafana.com/docs/grafana/latest/installation/docker/).

If you need to modify the grafana.ini you could copy it out to your host, modify accordingly then change the `docker-compose.yml` to mount back in your explicit copy.

**Comment by fleimgruber** [comment]
@nightah Would you say this is also the recommended approach if one wants to configure [Email](https://grafana.com/docs/grafana/latest/administration/configuration/#smtp)? If so, is the relevant grafana.ini located in `/etc/grafana/grafana.ini` within the container? And would the relevant mount section be something like this?

```
services:
  ...
  grafana:
    ...
    volumes:
      ...
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
```

**Comment by nightah** [comment]
@fleimgruber indeed, that's exactly how I have mine setup.

**Comment by fleimgruber** [comment]
@nightah thanks for checking back and the hints. Works over here.
