### ISSUE TITLE
Monitor docker volumes

### ISSUE THREAD

**Issue by PoweredByPeople** [stefanprodan/dockprom#170]
Hi, 

Have you had any success or know of a tool that allows monitoring of disk usage of local docker volumes? I've looked into the details of both cAdvisor and node exporter and neither seems to natively support monitoring docker volumes (located at /var/lib/docker/volumes). 

Is there any solution that could be built into this tool? For example if you were using dockprom to monitor a docker-compose deployed application stack that includes several different databases (mysql, cassandra, etc) it would be very valuable to see specifically the volume usage of those services. 

FYI the information is readily available with docker system df -v via the docker cli.

**Comment by nightah** [comment]
Honestly I would suggest maybe looking at the metrics export that comes directly from Docker:

https://docs.docker.com/config/thirdparty/prometheus/
https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-metrics

I personally haven't really seen if there are any other exporters that might provide said information but I would suggest that the Docker exporter is the first thing you should explore.

**Comment by logopk** [comment]
I have built an exporter with the go-docker api, locally served with a httpd server.

**Comment by nightah** [comment]
@PoweredByPeople might be worth giving that a try. I'm closing this issue off, if you have other issues please don't hesitate to open another one.
