### ISSUE TITLE
Docs: Add NodeExporter from a different host

### ISSUE THREAD

**Issue by fleimgruber** [stefanprodan/dockprom#174]
I can see that the local NodeExporter is configured to listen on port 9100 https://github.com/stefanprodan/dockprom/blob/c15864194960ec65e48dff2867d0a2f5bedb72aa/docker-compose.yml#L64

and then found the relevant config in https://github.com/stefanprodan/dockprom/blob/dbd8f15e1dc92cf46bfad6d61b4cc9cfb4ddfc45/prometheus/prometheus.yml#L19

Just to make sure that I am on the right track here and asking for how to best configure a Grafana dashboard for the NodeExporter on the other host. After I stitch it together, I would write up a PR to mention this in the docs. Please let me know if it is there already and I missed it.

**Comment by fleimgruber** [comment]
I now see that there are a few issues related to this: #171 #8 #52 #4

**Comment by nightah** [comment]
https://github.com/stefanprodan/dockprom/blob/master/docker-compose.exporters.yml

Is actually meant for this purpose, copy that to your respective hosts and run that up, if you don't want/need cadvisor from the other host just comment or remove it.

The templating of variables in Grafana can be done a couple of different ways and there are examples in those respective issues that you've linked to.

**Comment by fleimgruber** [comment]
> https://github.com/stefanprodan/dockprom/blob/master/docker-compose.exporters.yml

> Is actually meant for this purpose, copy that to your respective hosts and run that up, if you don't want/need cadvisor from the other host just comment or remove it.

Thanks, I was wondering about that and then found #90 and #5.

> The templating of variables in Grafana can be done a couple of different ways and there are examples in those respective issues that you've linked to.

It would be nice to have the different ways to do this and the matching examples collected in one place and documented accordingly as it seems this is a common use case for people using dockprom. Do you think that to be worthwile and would you accept the docs in dockprom?

I started with looking into the mentioned issues and distill the different ways with examples but did not find time last week. Also, I am quite new to Prometheus and Grafana and need to do some reading beforehand.

**Comment by nightah** [comment]
Sure thing, happy for you to submit it as a section in the README.md.

I've been meaning to move a lot of that out in to the wiki and fixing that up but honestly haven't had that much time to commit to doing so.

I'll be happy to review whatever you put together for inclusion.
