### ISSUE TITLE
configure dns all the services running within caddy

### ISSUE THREAD

**Issue by avanichy25** [stefanprodan/dockprom#177]
Hi,

currently we are using the same github to setup the monitoring via prometheus. All the services like grafana, promethues , node exporter, alertmanager are running behind caddy server and this is accessible via hostmachine ip :port. How to configure dns instead of ip address to access all the application.

**Comment by nightah** [comment]
https://caddyserver.com/docs/getting-started, alternatively if you have another reverse proxy you could put that infront of caddy.
