### ISSUE TITLE
How can i monitor Hyperledger Fabric metrics?

### ISSUE THREAD

**Issue by sfl0r3nz05** [stefanprodan/dockprom#180]
Hi,

I have created a HFB network and then I ran the dockprom. Right now i can mononitoring the status of HFB Nodes, however i need to go deeper, i.e., i need to monitoring the prometheus metrics defined by HFB in the [documentation](https://hyperledger-fabric.readthedocs.io/en/latest/metrics_reference.html?highlight=metrics#metrics-reference) (e.g., consensus_etcdraft_active_nodes, consensus_etcdraft_cluster_size and so on). I will appreciate any recomentation about how to configure prometheus.
![image](https://user-images.githubusercontent.com/6643905/82672469-af3be700-9c40-11ea-831e-0637d11a5fea.png)

**Comment by nightah** [comment]
I don't really know anything about HFB but looking at their docs the service exposes its own metrics which you will need to scape and add jobs for:

https://hyperledger-fabric.readthedocs.io/en/release-2.0/operations_service.html

You'll need to add jobs for each exporter here: https://github.com/stefanprodan/dockprom/blob/c83e819cfc488be4206942f95a745ed64e2945b0/prometheus/prometheus.yml#L15-L35

Like such:

```yaml
- job_name: ‘hyperledger_metrics’
    scrape_interval: 10s
    static_configs:
      - targets: [‘peer0.org1.example.com:9443’, ‘peer1.org1.example.com:9443’, ‘peer0.org2.example.com:9443’, ‘peer1.org2.example.com:9443’, ‘orderer.example.com:9443’]

**Comment by sfl0r3nz05** [comment]
Hi @nightah,

In addition to the configuration that you suggest, some environmental variables must be defined in docker compose file such as:
For orderer:
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer0.example.com:9443
      - ORDERER_METRICS_PROVIDER=prometheus
For peer:
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org1.example.com:9443
      - CORE_METRICS_PROVIDER=prometheus
I have created a [project ](https://github.com/sfl0r3nz05/HFB-Testing-Environment) to deploy Prometheuns on HFB.

Thanks, I will close the input.
