### ISSUE TITLE
Grafana entered the account password and returned to the login screen

### ISSUE THREAD

**Issue by chenzhangbo** [stefanprodan/dockprom#181]
Grafana entered the account password and returned to the login screen，I entered the correct username and password, and the page was logged in but returned to the login screen。

**Comment by nightah** [comment]
@chenzhangbo can you please provide more information?
The default username and password are `admin` unless you specified otherwise.

On initial setup it asks you to change the password, you can however skip that step.

**Comment by yappkahowe** [comment]
It happened to me after upgrading Grafana from 5.6.x to 7.0.x. My workaround is delete the cookies and login again.

**Comment by nightah** [comment]
@chenzhangbo I'm closing this off if issues persist please re-lodge an issue with an actual description to reproduce the problem.
