### ISSUE TITLE
Monitoring Services - no data for Memory usage and CPU usage

### ISSUE THREAD

**Issue by zilexa** [stefanprodan/dockprom#182]
I install everything via docker-compose and everything works out of the box except the "Memory Usage" number (empty) and the CPU usage graph (no data) and Memory usage graph (empty). 

When I check Prometheus, everything is up and running. So I thought I check a few of the datapoints that are used, for example for CPU usage. 
` container_cpu_user_seconds_total` is available in Prometheus and shows a long list of variables with datavalues. 
However I cannot find `container_label_org_label_schema_group`. It does not seem to exist. I have no clue what that means and what to replace it with?

I run everthing on an Intel based Ubuntu 19.10 machine. All my Docker containers are installed via a single docker-compose.yml file.

**Comment by nightah** [comment]
Unless you modified the default `docker-compose.yml` those labels are applied based on the following for each container:

```yaml
    labels:
      org.label-schema.group: "monitoring"
```
