### ISSUE TITLE
How to chang timezone Promethues

### ISSUE THREAD

**Issue by VietHebis** [stefanprodan/dockprom#183]
Timezone in host is Sat Jun 13 16:33:02 +07 2020 and time zone in Promethues container is Sat Jun 13 09:33:37 UTC 2020.
Could you help me edit timezone at container the same with time at my host ?

**Comment by nightah** [comment]
Is there any specific reason why? Grafana displays the data base on browser/local time.

https://prometheus.io/docs/introduction/faq/#can-i-change-the-timezone-why-is-everything-in-utc.
