### ISSUE TITLE
"HTTP Error Bad Gateway” when adding Prometheus as datasource

### ISSUE THREAD

**Issue by assist726** [stefanprodan/dockprom#184]
I can access Prometheus correctly through browser at http://localhost:9090 with my docker-compose file being unedited from default configurations

However when adding Prometheus as datasource in Grafana I receive the "HTTP Error Bad Gateway” error. I have also tried a few different URLs as suggested online to no avail:

http://localhost:9090
http://127.0.0.1:9090
http://host.internal.docker:9090

and via finding IP through:
docker inspect prometheus

`"Networks": {
                "dockprom_monitor-net": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "1bcc4a37c19d",
                        "prometheus"
                    ],
                    "NetworkID": "caacbb5c4fa1d6ddacde5eb3e8005dd932c1be0a439fc4b5f37ee2bb9b74235e",
                    "EndpointID": "001094e31990bbc8f2e07cec69296e648ca49514084a9d66353bc1d63b2e4538",
                    "Gateway": "172.20.0.1",
                    "IPAddress": "172.20.0.6",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:14:00:06",
                    "DriverOpts": null
                }
            }`

http:/172.20.0.6:9090
http:/172.20.0.1:9090

**Comment by nightah** [comment]
The datasource in Grafana should be `http://prometheus:9090`, this should also be created during initial setup.
