### ISSUE TITLE
Run on RPI?

### ISSUE THREAD

**Issue by koralilgun** [stefanprodan/dockprom#185]
I have been running dockprom on Ubuntu and love it. I'd love to be able to run it on a RPI also. Unfortunately, when I docker-compose up, caddy and cadvisor go into a restart loop and their docker logs contain the same error:
`standard_init_linux.go:211: exec user process caused "exec format error"`
Any suggestions on how I might be able to run dockprom on an RPI with Raspbian?

**Comment by nightah** [comment]
There isn't an official cadvisor image for the ARM architecture; https://github.com/google/cadvisor/issues/1236.

The caddy image we use is maintained by @stefanprodan, it'd be pretty straight forward to update that for ARM support, but realistically you would need to modify your `docker-compose.yml` yourself and use one of the ARM compiled containers in that thread for cadvisor.

**Comment by skywinder** [comment]
same questions, same issue. @koralilgun did you check any workarounds?
