### ISSUE TITLE
Can't install dockprom

### ISSUE THREAD

**Issue by Culla95** [stefanprodan/dockprom#186]
So I just run the commands to install it and everything starts correctly, cadvisor, nodexporter and pushgateway  had no problems but for caddy, prometheus and grafana i get this error: 

> ERROR: for caddy  Cannot create container for service caddy: status code not OK but 500: {"Message":"Unhandled exception: Filesharing has been cancelled","StackTrace":"   en Docker.ApiServices.Mounting.FileSharing.<DoShareAsync>d__6.MoveNext() en C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\Mounting\\FileSharing.cs:lĂ­nea 0\r\n--- Fin del seguimiento de la pila de la ubicaciĂłn anterior donde se produjo la excepciĂłn ---\r\n   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Docker.ApiServices.Mounting.FileSharing.<ShareAsync>d__4.MoveNext() en C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\Mounting\\FileSharing.cs:lĂ­nea 47\r\n--- Fin del seguimiento de la pila de la ubicaciĂłn anterior donde se produjo la excepciĂłn ---\r\n   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Docker.HttpApi.Controllers.FilesharingController.<ShareDirectory>d__2.MoveNext() en C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.HttpApi\\Controllers\\FilesharingController.cs:lĂ­nea 21\r\n--- Fin del seguimiento de la pila de la ubicaciĂłn anterior donde se produjo la excepciĂłn ---\r\n   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicaciĂłn anterior donde se produjo la excepciĂłn ---\r\n   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicaciĂłn anteCreating grafana      ... error                                                                                          System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicaciĂłn anterior donde se produjo la excepciĂłn ---\r\n   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()"}

So what am I doing wrong?

**Comment by nightah** [comment]
Not all the containers support deployment on windows so this is really an upstream issue.

At this stage dockprom is only supported on Linux.

**Comment by Culla95** [comment]
I actually maged to make it run in windows. The steps I followed were:

1. Install an older version of Docker Desktop(19.03.1)
2. Set all the images to Latest in the YML
3. Change all the "- /:/rootfs:ro" to "- c:\:/rootfs:ro" in the YML

I was able to run it this way.
