### ISSUE TITLE
http: superfluous response.WriteHeader call

### ISSUE THREAD

**Issue by mkshb** [stefanprodan/dockprom#188]
Hey there, 

within cadvisor logs i get following errors:

cadvisor             | W0703 09:14:05.375042       1 manager.go:256] Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: no such file or directory
cadvisor             | 2020/07/03 09:14:13 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:306)
cadvisor             | 2020/07/03 09:14:18 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:306)

No Docker data is written to promentheus anymore.

Thanks in advance

**Comment by martinfar** [comment]
Same issue

**Comment by nightah** [comment]
This issue has been resolved upstream https://github.com/google/cadvisor/pull/2605, we're just waiting for there to be an actual release which includes the changes, as soon as something is available I'll be sure to pull it in.
