### ISSUE TITLE
Incomplete dashboards on WSL2

### ISSUE THREAD

**Issue by chintanp** [stefanprodan/dockprom#190]
I am trying to use dockprom on WSL2 (Windows 10 Build1904). I am able to login to Grafana and find the pre-configured dashboards - "Docker Containers", "Docker Host", "Monitor Services" and "Nginx".

However, the dashboards seem incomplete as can be seen in the image below: 

![image](https://user-images.githubusercontent.com/752869/87234713-94f0d080-c388-11ea-9f09-b1affd7dd3dd.png)

I definitely have one other docker-compose set running besides dockprom. 

Logs for Grafana, Prometheus, caddy, pushgateway and alertmanager seem fine. 

Node-exporter has "couldnt get netstats" etc errors. Some logs in pastebin here: https://pastebin.com/AQXsZmQQ

cAdvisor also seems to have error(s) `"80506cf5c706ad68e7e14304949304e86fdb41bb477b4e4036f68073fae869a8". - open /rootfs/var/lib/docker/image/overlay2/layerdb/mounts/80506cf5c706ad68e7e14304949304e86fdb41bb477b4e4036f68073fae869a8/mount-id: no such file or directory` . A few lines in pastebin here: https://pastebin.com/5tHnaVZA

Any ideas on debugging this would be helpful.

**Comment by chintanp** [comment]
[This ](https://askubuntu.com/questions/1161129/netstat-command-on-wsl-doesnt-give-any-messages) says `netstat` is not supported on WSL. Maybe that is the issue. Has anyone been able to make this work on WSL.

**Comment by nightah** [comment]
@chintanp I'd suggest lodging the issue upstream to both [node-exporter](https://github.com/prometheus/node_exporter/) and [cadvisor](https://github.com/google/cadvisor/) I don't see anything in the former that suggests it would or would not work in WSL, though lots of issues and comments in PR's for not supporting Windows, there's a separate exporter for that.

**Comment by woss** [comment]
is there any way to have this on wsl2? i was looking for the solution but this repo https://github.com/docker-archive/infra-container_exporter is archived.

**Comment by chintanp** [comment]
@woss haven't tested it, but I think @nightah was referring to the Windows Exporter: https://github.com/prometheus-community/windows_exporter
