### ISSUE TITLE
Remove pass prometheus alertmanager

### ISSUE THREAD

**Issue by Gum97** [stefanprodan/dockprom#193]
Hi Bro,
i need remove passwd login prometheus and alertmanager to install prometheus telegram bot, maybe can help me?

**Comment by nightah** [comment]
Remove the respective basicauth lines at the following two locations:

https://github.com/stefanprodan/dockprom/blob/33ea819868b52c35c4b4924381e9368e8e1045fa/caddy/Caddyfile#L2

https://github.com/stefanprodan/dockprom/blob/33ea819868b52c35c4b4924381e9368e8e1045fa/caddy/Caddyfile#L12
