### ISSUE TITLE
Missing metrics

### ISSUE THREAD

**Issue by Azbesciak** [stefanprodan/dockprom#195]
Hello, I think it is not the issue of this configuration, but many people use this config and might face the same issue.
I wanted to monitor the average request response time, quintiles, errors count, request count, most often IPs, etc.
I found that it is possible with for example `http_request_total` - but it is not available in the Prometheus.
I read somewhere that there is `promhttp_metric_handler_requests_total`, and indeed - there is something like this, but returns something different.

How to solve this problem? I see that `http_request_total` is not something unique and commonly used, for example, https://blog.softwaremill.com/practical-monitoring-with-prometheus-ee09a1dd5527.

Thanks!

**Comment by nightah** [comment]
@Azbesciak can you clarify you want to see those metrics from what specific service, Prometheus itself or?

**Comment by Azbesciak** [comment]
@nightah from all containers

**Comment by nightah** [comment]
So the only thing that exists within the stack is `prometheus_http_requests_total` which returns the values against a specific URI/path and the associated http status code.

I'd suggest you look into a prometheus exporter specifically for your reverse proxy (nginx, Traefik, HAProxy) and utilise that to get the information you seek.

**Comment by nightah** [comment]
@Azbesciak I'm going to close off this issue, if you have any other questions please don't hesitate to open another issue.
