### ISSUE TITLE
nodeexporter will not export network stats

### ISSUE THREAD

**Issue by debuglevel** [stefanprodan/dockprom#198]
https://github.com/stefanprodan/dockprom/blob/7973b22969c203ab19a285457bd0af4dd9bb5964/docker-compose.yml#L65-L66

Please note that nodexporter will probably export the containers network stats, but not the the hosts network stats.
For my standalone nodeexporter, I fixed this via `    network_mode: "host"`. But I don't know if this would work well with the other services in your docker-compose.yml

**Comment by nightah** [comment]
Hi @debuglevel that's what https://github.com/stefanprodan/dockprom/blob/master/docker-compose.exporters.yml is intended for.

Either way whether you modify the main compose or use node-exporter from the other compose file you will need to modify the actual dashboard to pick up the respective NIC.
