### ISSUE TITLE
Using with Kubernetes?

### ISSUE THREAD

**Issue by manojlds** [stefanprodan/dockprom#2]
Any thoughts on using this with Kubernetes?

**Comment by stefanprodan** [comment]
To make this work with Kubernetes you have to use [kubernetes_sd_config](https://prometheus.io/docs/operating/configuration/#<kubernetes_sd_config>) so Prometheus can discover the pods. Weave has a great write-up on [Prometheus and Kubernetes](https://www.weave.works/prometheus-and-kubernetes-monitoring-your-applications/).

**Comment by sohel2020** [comment]
@stefanprodan I liked your dashboard very much could you please give me a dashboard for kubernetes server and container monitoring. 

Another question is how I can monitor my application end point, such as my website?  and plot a graph as a service availability graph and after end of the month to show management as a service availability report.
