### ISSUE TITLE
I wanted to add domain name instead of using <host-ip>

### ISSUE THREAD

**Issue by avanichy25** [stefanprodan/dockprom#201]
Hi, 

I wanted to add domain name for grafana using caddy. Please assist.

Currently using the caddy 
```
:3000 {
    proxy / grafana:3000 {
            transparent
            websocket
        }

    errors stderr
    tls off
}
```

Thanks !

**Comment by nightah** [comment]
Any customisations to the underlying Caddy webserver will work according to the [documentation](https://caddyserver.com/docs/).

I usually have a reverse proxy sitting in front of Caddy so that's where any of the hostname and server name specifications go.
