### ISSUE TITLE
Caddy v1 Broken with Docker v20.10.0

### ISSUE THREAD

**Issue by joesixpack** [stefanprodan/dockprom#203]
The latest Docker v20.10.0 update appears to have broken Caddy which is also very old and outdated at v1.

`goroutine 1 [running]:
github.com/mholt/caddy/vendor/github.com/miekg/dns.ClientConfigFromFile(0xbb4739, 0x10, 0x0, 0x0, 0x0)
        src/github.com/mholt/caddy/vendor/github.com/miekg/dns/clientconfig.go:86 +0xad6
github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.getNameservers(0xbb4739, 0x10, 0xfeaf20, 0x2, 0x2, 0xf77460, 0xc42004c2c0, 0xc420043f50)
        src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:40 +0x4d
github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.init()
        src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:33 +0x12d
github.com/mholt/caddy/caddy/caddymain.init()
        <autogenerated>:1 +0x75
main.init()
        <autogenerated>:1 +0x44
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/mholt/caddy/vendor/github.com/miekg/dns.ClientConfigFromFile(0xbb4739, 0x10, 0x0, 0x0, 0x0)
        src/github.com/mholt/caddy/vendor/github.com/miekg/dns/clientconfig.go:86 +0xad6
github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.getNameservers(0xbb4739, 0x10, 0xfeaf20, 0x2, 0x2, 0xf77460, 0xc42004c2c0, 0xc420043f50)
        src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:40 +0x4d
github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.init()
        src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:33 +0x12d
github.com/mholt/caddy/caddy/caddymain.init()
        <autogenerated>:1 +0x75
main.init()
        <autogenerated>:1 +0x44
panic: runtime error: slice bounds out of range
`

**Comment by nightah** [comment]
I do not have this issue with Arch Linux and Docker `20.10.1`.
Can you retest with `20.10.1` and report your findings?

Also it's probably worth asking what Architecture is the machine you are running dockprom on?

**Comment by joesixpack** [comment]
I'm on Ubuntu 20.04 LTS amd64, but that newer Docker .1 update probably fixed things.  I've already switched to Caddy v2 though.

**Comment by nightah** [comment]
Sure well either way I don't believe this is reproducible and isn't an issue with Caddy either way.

If you find you are experiencing issues again let me know and we can reopen the issue.

**Comment by apit** [comment]
pop!os 20.10 LTS amd64 docker 20.10.1 has this issue. using caddy:1.0.3 image fixed it

**Comment by bhumijgupta** [comment]
I has the same issue with Ubuntu 20.04 LTS amd64 config running on AWS EC2 instance.
Ended up porting the config to Caddy v2 and using it.
