### ISSUE TITLE
Problem on RPI

### ISSUE THREAD

**Issue by Ghils1** [stefanprodan/dockprom#204]
Hello 

First thanks for your work.

I tried to install dockprom on an RPI, but cadvisor and caddy containers fails.
As others works, I handle this by publishing port..

I would prefer to run all container, so I tried to build caddy locally.
But it fails due to credentials errors:

 ---> 3f0e42d9a234
Step 4/17 : RUN git clone https://github.com/mholt/caddy -b "v$CADDY_VERSION" /go/src/github.com/mholt/caddy     && cd /go/src/github.com/mholt/caddy     && git checkout -b "v$CADDY_VERSION"
 ---> Running in 155b99d9a8ab
Cloning into '/go/src/github.com/mholt/caddy'...
fatal: could not read Username for 'https://github.com': No such device or address

Regards.

**Comment by levesduzw** [comment]
Hi, Caddy worked for me with https://hub.docker.com/r/elswork/arm-caddy. One more change in docker-compose.yml:
```
volumes:
      - ./caddy:/etc/
```

**Comment by hfyeomans** [comment]
Hello - I wanted to get this to work on RPi as well so I changed to use caddy v2.3.0, changed the v1 config all around to be a v2 config instead. I'm using zcube/cadvisor for the cadvisor part.  So far so good.  I saw #207 and #208 regarding caddy and my Caddyfile is the same, very simple config.  If there's information that I can help with please let me know.  I've not been running it long, maybe 2-3 hours as of writing.

**Comment by nightah** [comment]
This issue should be resolved in v3.30.0.
