### ISSUE TITLE
Update Caddy to v2

### ISSUE THREAD

**Issue by bhumijgupta** [stefanprodan/dockprom#206]
Currently the Caddy image that is used is on v1. Since then v2 has been released which is much more stable. It would be helpful if this could be ported to use the official v2 image.
Also there have been issue with older version of Caddy and newer version of Docker(See https://github.com/stefanprodan/dockprom/issues/203).

I would like to take up the issue and create a PR if approved.

**Comment by nightah** [comment]
@bhumijgupta looks like someone has already attempted this at #207.
Please follow progress at that PR.

**Comment by bhumijgupta** [comment]
@nightah The PR seems to be stale. I'll open a new PR with the suggested changes and some more minor changes
