### ISSUE TITLE
Email as a notification receiver

### ISSUE THREAD

**Issue by diriy** [stefanprodan/dockprom#210]
Could you please add to documentation what should I do for to configure email sending as a notifier instead of slack?

**Comment by nightah** [comment]
It's documented over at the [Alertmanager](https://prometheus.io/docs/alerting/latest/configuration/#email_config) docs page.

You can find an example of the alertmanager `config.yml` below:

```yml
route:
    receiver: 'email'

receivers:
    - name: 'email'
      email_configs:
          - send_resolved: true
            to: 'alertmanager@example.com'
            from: '"Alertmanager" <alertmanager@example.com>'
            smarthost: 'mail.example.com:25'
            auth_username: 'user@example.com'
            auth_password: 'passwordhere'
            html: '{{ template "email.default.html" . }}'

**Comment by diriy** [comment]
@nightah , unfortunately, the problem still exist. any help appreciated.
