### ISSUE TITLE
Pulling cadvisor Error

### ISSUE THREAD

**Issue by freewheel70** [stefanprodan/dockprom#212]
Hi, I encounter the following error when executing `docker-compose up -d`

```
Pulling cadvisor (gcr.io/cadvisor/cadvisor:v0.38.7)...
ERROR: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

```
Is there any specific reason to use this version of cadvisor ? why not google/cadvisor ?

**Comment by nightah** [comment]
Because `google/cadvisor` only gets the canary tag written and hasn't been [updated in years](https://hub.docker.com/r/google/cadvisor/tags?page=1&ordering=last_updated).

All the up-to-date containers are deployed onto gcr.

**Comment by nightah** [comment]
The issue is likely to have been a transient network issue and not related to the location where the container is hosted, if you still have issues please let me know and we can reopen this issue.
