### ISSUE TITLE
Add variable to filter by docker-compose projects/stacks 

### ISSUE THREAD

**Issue by psychowood** [stefanprodan/dockprom#217]
Hi,
here's my simple use case:

1. Local docker host
2. Different docker-compose projects
3. Filter container stats by compose project name

Basically, I added a variable on top of the dashboard, based on `label_values(container_label_com_docker_compose_project)` and injected it in every query below, by adding `,container_label_com_docker_compose_project=~"$compose_projects"` everywhere except on the top row (CPU/Memory/Storage Load).

It would be nice to have the aggregated stat too (i.e. total memory used by a stack) but my grafana skills are more or less 1 hour old, I need more time :)

![image](https://user-images.githubusercontent.com/115389/109710593-21613500-7b9e-11eb-9346-7f812e6af73b.png)

I could provide a PR for the provisioning file if you believe this could be useful.

**Comment by Seth1u** [comment]
I don't find networks mectics dashboard 
![image](https://user-images.githubusercontent.com/45417068/112701911-3033c280-8e92-11eb-982d-adbb0c88f975.png)

Can you tell me how to prompt it? Thanks

**Comment by nightah** [comment]
I actually do something very similar with [Docker Compose stacks myself](https://nerv.cx/XLwYT) this does actually take memory usage into account for the selected stack too.

Here's the [configuration pane for the variable](https://nerv.cx/N2byj).

And the relevant configuration that needs to be added to each of the panels is the section bolded below (Used Memory panel as an example):

sum(container_memory_usage_bytes{image!="",**container_label_com_docker_compose_project=~"$stack"**})

**Comment by Seth1u** [comment]
![image](https://user-images.githubusercontent.com/45417068/112900654-11c50580-90e4-11eb-913e-58942aa2029f.png)

![image](https://user-images.githubusercontent.com/45417068/112900770-30c39780-90e4-11eb-976d-773fedc13b0e.png)

I chabge it like u but same errors, no containers show up 

![image](https://user-images.githubusercontent.com/45417068/112900877-53ee4700-90e4-11eb-82bc-fa6da60a0779.png)
