### ISSUE TITLE
Running the node exporter on the host rather than in the container

### ISSUE THREAD

**Issue by crawfs** [stefanprodan/dockprom#222]
Hey, I've been using this for a few weeks great project and easy to use. Just wondering if there is any interest in maintaining a version that allows the node exporter to be run on the docker host rather than via a container. I've currently done this manaully by removing the node exporter container from the docker-compose.yml file and modifying the config in the prometheus,yml file to point to the host instead of the container.

The issue with this solution is that I have to do it over again if I need to pull down the repo again to my local and it would be a bit more convenient if it was available as an option.

**Comment by nightah** [comment]
That's actually what this is included for.

https://github.com/stefanprodan/dockprom/blob/051e780e59181ac80723ede3a17b363775c381a1/docker-compose.exporters.yml#L5-L20

You can just model the instance of node-exporter in the main docker-compose to utilise the `network_mode: host`.

The only other change you need to make for this to work is the following line too:

https://github.com/stefanprodan/dockprom/blob/051e780e59181ac80723ede3a17b363775c381a1/prometheus/prometheus.yml#L19

This would need to represent the IP address/hostname of your host Docker host.
