### ISSUE TITLE
Prometheus docker_sd_configs

### ISSUE THREAD

**Issue by roidelapluie** [stefanprodan/dockprom#223]
Hello community o/

Starting with Prometheus 2.27, we will offer a native docker sd discovery fordocker containers (without swarm).

Feedback welcome, you can test it with the prom/prometheus:main docker image (I do not recommend using the main in production).

Documentation: https://github.com/prometheus/prometheus/blob/main/docs/configuration/configuration.md#docker_sd_config

**Comment by nightah** [comment]
Thanks for the info!
