### ISSUE TITLE
To open or to not open public ports

### ISSUE THREAD

**Issue by pascalandy** [stefanprodan/dockprom#23]
It make sense to open grafana port to the public.

But I'm not not sure to understand why **prometheus** and **alertmanager** have their port public. Any particular reason for this behaviour?

Many cheers!

**Comment by stefanprodan** [comment]
I'm guessing you want to view alerts and be able to silence them, as for Prometheus you can monitor the targets, write queries and more. I will update the project and I'll include a reverse proxy with basic auth for those two.

**Comment by stefanprodan** [comment]
@pascalandy I've added the reverse proxy with basic auth, can you please test it out?

**Comment by pascalandy** [comment]
Cannot start compose.

```
root@vps01:~/dockprom# docker-compose up -d
ERROR: Invalid interpolation format for "environment" option in service "caddy": "ADMIN_USER=${ADMIN_USER:-admin}"
```

**Comment by stefanprodan** [comment]
Looks like inline defaults are supported in compose 2.1, should work now.

**Comment by pascalandy** [comment]
humm

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
Aborting due to errexit on line 26. Exit code: 1

**Comment by stefanprodan** [comment]
can you please post `docker-compose -v`

**Comment by pascalandy** [comment]
On 1.8.0 and I see we are now at 1.16.1 !
https://github.com/docker/compose/releases

**Comment by stefanprodan** [comment]
No, compose comes only with Docker for Mac, on linux you have to update via:

```
curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

**Comment by pascalandy** [comment]
Updated. Compose is running.

```
ERROR: for caddy  Cannot start service caddy: driver failed programming external connectivity on endpoint caddy (68b28af87Creating grafana ... done

ERROR: for caddy  Cannot start service caddy: driver failed programming external connectivity on endpoint caddy (68b28af8726c3582076d5a26fe40746b46ec61361202aa23705cff77d00f144b): Bind for 0.0.0.0:9093 failed: port is already allocated
```

**Comment by stefanprodan** [comment]
That's because you are running the older version with prometheus exposing port 9093.

You have to remove the stack with:

```
docker-compose down -v
```

And run the new one with:

```
ADMIN_USER=admin ADMIN_PASSWORD=admin docker-compose up -d
```

After that your prometheus and alermanager services will require user/pass.

**Comment by stefanprodan** [comment]
Ok, thanks for testing, I've updated the readme with the minimum required Docker Compose version.

**Comment by pascalandy** [comment]
Sorry for the confusion earlier. I meant, compose is now installed properly.

All the container behave normally. But there is nothing on those 3 ports :-/

Prometheus (metrics database) http://<host-ip>:9090
AlertManager (alerts management) http://<host-ip>:9093
Grafana (visualize metrics) http://<host-ip>:3000

**Comment by stefanprodan** [comment]
It was  problem with the mount point for Caddy, should work now.

**Comment by pascalandy** [comment]
Yes! This is solid now :)
