### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by behrad** [stefanprodan/dockprom#237]
I have an old version dockprom with prometheus 2.24 but I need >= 2.26 
So I want to pull latest dockprom but I didn't find any update instructions.
Should I run `docker compose up` again after pulling latest dockprom?

**Comment by nightah** [comment]
If a release has breaking changes they're included in said release notes.

You should check before updating, considering you have Prometheus 2.24 you'll notice the following release and migration notes:

https://github.com/stefanprodan/dockprom/releases/tag/v3.30.0
https://github.com/stefanprodan/dockprom#updating-caddy-to-v2

**Comment by behrad** [comment]
thank you @nightah but may be it would be more clear if release notes was linked inside README
And how could I grab my current dockprom version?

**Comment by nightah** [comment]
The breaking changes are linked inside the README.

To see which version your current commit of dockprom corresponds to you can look up tags based on your commit:

```
git tag --contains `git rev-parse HEAD`
