### ISSUE TITLE
Install issues for cadvisor

### ISSUE THREAD

**Issue by jgiddens** [stefanprodan/dockprom#238]
Hello,

I am installing this container pack on an unprivileged LXC container on Proxmox PVE 7.  The container is based on the ubuntu 21.04 template and all packages are up to date and current.  I have cloned the repository and cut and pasted your default docker-compose startup command (with the admin passwords, etc.)  This is what I get:

```
ERROR: for cadvisor  Cannot start service cadvisor: error gathering device information while adding custom device "/dev/kmsg": no such file or directory
ERROR: Encountered errors while bringing up the project.
```
What am I doing wrong?

**Comment by nightah** [comment]
Based on my most recent testing binding `/dev/kmsg` into the container alone via the `devices` option is not enough, you need to enable the privileged flag on the container too.

You can try remove the whole `devices` option in the `docker-compose.yml` you just won't get OOM events which isn't really a big deal.

**Comment by jgiddens** [comment]
That did the trick!  Thanks

**Comment by nightah** [comment]
No problems, glad you got it sorted!
