### ISSUE TITLE
Use Grafana 8.3.2

### ISSUE THREAD

**Issue by PHPGangsta** [stefanprodan/dockprom#249]
Update Grafana to 8.3.2 because of the latest security bugfixes:

https://grafana.com/blog/2021/12/07/grafana-8.3.1-8.2.7-8.1.8-and-8.0.7-released-with-high-severity-security-fix/
https://grafana.com/blog/2021/12/10/grafana-8.3.2-and-7.5.12-released-with-moderate-severity-security-fix/

**Comment by nightah** [comment]
Closed by https://github.com/stefanprodan/dockprom/commit/3cb9bb0cfc03d0427dd0a09c3a4c1bd5ef208935 in v4.15.2.
