### ISSUE TITLE
Show some last lovin' for Docker Swarm, update readme

### ISSUE THREAD

**Issue by bluepuma77** [stefanprodan/dockprom#254]
When searching for "Docker Swarm Prometheus" your [swarmprom](https://github.com/stefanprodan/swarmprom) project is all over in the results, sad to see it archived.

1. Please remove "If you're looking for the Docker Swarm version please go to stefanprodan/swarmprom" from [dockprom readme](https://github.com/stefanprodan/dockprom) as that is (currently) a dead end.

2. Please add a statement to dockprom about Docker Swarm usage (examples):
a) "dockprom can not be used with Docker Swarm"
b) "dockprom can be used with Docker Swarm with [a Docker API proxy](https://github.com/prometheus/prometheus/discussions/9640#discussioncomment-1572760) and [Prometheus Docker Swarm service discovery](https://prometheus.io/docs/guides/dockerswarm/)"
c) "dockprom can be used with Docker Swarm but its unimaginable complicated, therefore not recommended"

3. If dockprom can be used with Docker Swarm, please put a back-link in [swarmprom](https://github.com/stefanprodan/swarmprom) so people can find dockprom.

4. Optional icing on the cake: If another maintainer stepped up for swarmprom and maintains it in another repo, it would be nice to link to it in [swarmprom](https://github.com/stefanprodan/swarmprom). swarmprom currently has 642 forks, but I have no idea how to find a currently maintained version.

**Comment by nightah** [comment]
The latter points are probably more a question for @stefanprodan I don't run Swarm and have no interest in maintaining the repo.

Happy to add in 1 and 2 here though.

**Comment by stefanprodan** [comment]
Thanks @nightah, please update the readme. As for no3 I don't think dockprom is the best solution for Swarm.

**Comment by s4ke** [comment]
I hope it's fine to comment here, since I just found out today that this repo existed. We love the original swarmprom and decided to port it to newer versions. We maintain a stack based on it over here https://github.com/neuroforgede/swarmsible-stacks/tree/main/02_monitoring
