### ISSUE TITLE
Storage capacity incorrect when bind mounts used

### ISSUE THREAD

**Issue by ninjamonkey198206** [stefanprodan/dockprom#256]
I'm not sure if it's the bind mounts specifically, but I've got a Ubuntu 20.04 VM running using Google Compute with a 20GB OS vhd and a 500GB storage vhd.

In order to keep Docker volumes from overwhelming the normally more than adequate 20GB OS vhd, I changed the storage vhd mount in fstab to /Storage.

I created folders for ownCloud file storage (not docker based) and Docker on the Storage vhd, then set bind mounts in fstab for them. 

After transferring the files to the new locations, everything worked splendidly.

I then installed and configured this stack to match the fs and found that the Free Storage showed roughly 1.2TB, which makes it seem like it is interpreting the bind mounts as separate drives.

I have no idea if there is anything that can be done about this, as this is out of my wheelhouse, and it's not really an issue if you know your system, but I thought you might want to know in case there actually is something you can do about it. My thought was to have it ignore bind mounts, but I have no idea if that's possible or not.

**Comment by nightah** [comment]
You can see all the detected filesystems by running the following expression `node_filesystem_free_bytes` either in Prometheus or in the Grafana Explore section.

From there you can determine which filesystems you do or don't want to include in the displayed query.
