### ISSUE TITLE
change port 9090

### ISSUE THREAD

**Issue by duckmeimfamous** [stefanprodan/dockprom#257]
Hi, could you please change port 9090, it's used bu cockpit or other services for a lot of us :)

**Comment by Mikhail566** [comment]
I also have such a question.  It would be great to make a configuration file where you could set a port for each service.

**Comment by nightah** [comment]
You can do this with Docker by modifying the `docker-compose.yml`, specifically the following lines:

https://github.com/stefanprodan/dockprom/blob/master/docker-compose.yml#L123-L127

The left side of the port mapping is the port for the host.
