### ISSUE TITLE
how to handle alerts for a large group of somehow same container ?

### ISSUE THREAD

**Issue by ImmoWetzel** [stefanprodan/dockprom#259]
I do have 100 container to control.
so I need to replace name=jenkins into name=simulators.*
this means I do have a cpu usage alert like
rate﻿(﻿container_cpu_usage_seconds_total﻿{﻿name﻿=~﻿"simulators-.*"﻿}﻿[﻿1m﻿]﻿)﻿ / ﻿count﻿(﻿node_cpu_seconds_total﻿{﻿mode﻿=﻿"system"﻿}﻿)﻿ * ﻿100﻿ ﻿>﻿ ﻿3
but this doesnt work. 
Any proposal ?

**Comment by nightah** [comment]
I'm not exactly sure if you're asking about Grafana Alerts or otherwise.

Can you describe what specifically you're having issues with?
