### ISSUE TITLE
node exporter failed

### ISSUE THREAD

**Issue by yunchih** [stefanprodan/dockprom#26]
Hi @stefanprodan :

with `node_exporter` 0.15.0 I am getting the following error message:

```
node_exporter: error: unknown short flag '-c', try --help
```

I have to add the following patch:
```
diff --git a/docker-compose.yml b/docker-compose.yml
index 6a65bff..9a1403a 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -56,9 +56,9 @@ services:
       - /sys:/host/sys:ro
       - /:/rootfs:ro
     command:
-      - '-collector.procfs=/host/proc'
-      - '-collector.sysfs=/host/sys'
-      - '-collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
+      - '--path.procfs=/host/proc'
+      - '--path.sysfs=/host/sys'
+      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
```

If you also confirm this as an issue, maybe allow me to make a PR to fix it, for the sake of [this](https://hacktoberfest.digitalocean.com/) 😆.

I will also modify `docker-compose.exporters.yml` as necessary.

I think it'd be good to pin `node_exporter` to a specific version, say `0.14.0`, what do you think?

**Comment by stefanprodan** [comment]
Ok let's go for Node Exporter 0.15 and Prometheus 1.8, please make a PR with the compose changes as well. 

Thanks
