### ISSUE TITLE
Grafana v9.1.1 (9e60a1bff1) show no preconfigured dashboards by default

### ISSUE THREAD

**Issue by saukrs** [stefanprodan/dockprom#275]
I use Docker `20.10.21` + Compose plugin `v2.12.2` on updated Linux Mint 21.

If I clone the repo and run this command:
```
ADMIN_USER=admin ADMIN_PASSWORD=admin ADMIN_PASSWORD_HASH=JDJhJDE0JE91S1FrN0Z0VEsyWmhrQVpON1VzdHVLSDkyWHdsN0xNbEZYdnNIZm1pb2d1blg4Y09mL0ZP docker compose up -d
```
(notice the `docker compose` without a dash, as was in the original snippet: `docker-compose`)

... the initial Grafana view is empty. I get no preconfigured dashboards:
![Screenshot from 2022-11-08 13-44-45](https://user-images.githubusercontent.com/117377007/200559873-9d1e79f9-a5d9-4c81-be16-2d43c738fbd5.png)

**Comment by saukrs** [comment]
This is what my Grafana homepage page looks like (http://localhost:3000/?orgId=1).

OK, some preconfigured dashboards seems to be actually present on my install:
http://localhost:3000/alerting/list?search=open&query=

![Screenshot from 2022-11-08 15-31-06](https://user-images.githubusercontent.com/117377007/200577675-96244908-3000-4149-a029-9283f9dfe212.png)

... only that I expected to see one of them to be set as Grafana Home dashboard:
https://stackoverflow.com/questions/48164754/how-to-set-a-dashboards-on-grafana-home-page/48212294#48212294

**Comment by nightah** [comment]
As you have discovered the Dashboards are present, as far as setting the default Dashboard, there's multiple ways to address this however I can't see any mechanism to do that on provisioning because of the different layers the default can be set.
