### ISSUE TITLE
How to have Docker Container dashboard show the containers used for monitoring?

### ISSUE THREAD

**Issue by MarioIshac** [stefanprodan/dockprom#278]
From the README:

"Note that this dashboard doesn't show the containers that are part of the monitoring stack."

Looking through the repository, I can't find the specific place where these monitoring stack containers are exempted from the Prometheus metric aggregation. Where would I be able to enable their tracking?

**Comment by nightah** [comment]
There's a Dashboard called `Monitoring Services`, the query utilised for those containers is as follows: `container_label_org_label_schema_group="monitoring"` and you'll notice the other dashboards have the following in their queries: `container_label_org_label_schema_group=""` which excludes the monitoring dashboards.
