### ISSUE TITLE
Duplicate container names

### ISSUE THREAD

**Issue by kroese** [stefanprodan/dockprom#284]
I monitor multiple machines (via the node export yml).

But some container-names are the same between machines. In Grafana I see these names only once..

So how is this handled? Does it sum all stats for duplicate containers together? Or does it just show the first one and ignores the other ones?

In that last case, couldn't it just add an incremental value (name2, name3) to the names?

**Comment by nightah** [comment]
I would be using another field as a variable to switch between nodes/hosts.

Here's an example that I utilise for the Docker Containers Dashboard to be able to filter based on the Docker Stack and/or the individual container name.

![raw](https://github.com/stefanprodan/dockprom/assets/3339418/379b38c5-6153-4c6b-adf3-877e49d7193e)
