### ISSUE TITLE
Where is the dockprom_network configuration?

### ISSUE THREAD

**Issue by jtencioc101** [stefanprodan/dockprom#285]
I have been searching where the dockprom_proxy network is declared.
This seems to be created automatically, can you please confirm where is it declared?
```
Creating network "dockprom_proxy" with driver "bridge"
```

**Comment by nightah** [comment]
We have no such network defined in the compose file. This is likely a modification that has been made manually.

See the network that we define at the following location: https://github.com/stefanprodan/dockprom/blob/76a5131e8742c01e3ec859f4bd828c4cdafeb1f9/docker-compose.yml#L3-L5
