### ISSUE TITLE
Angular Deprecation in Grafana

### ISSUE THREAD

**Issue by ameer1234567890** [stefanprodan/dockprom#294]
Now that AngularJS is being deprecated in grafana, are there any plans to move the dashboard to React?

https://grafana.com/docs/grafana/latest/developers/angular_deprecation/

**Comment by nightah** [comment]
My understanding is that when Angular is deprecated that this will automatically change said panels to their new variant.
If you want to get rid of the warnings ahead of time you can add the following to your `grafana.ini` at the bottom:

```ini
[feature_toggles]
autoMigrateOldPanels = true
```

**Comment by ameer1234567890** [comment]
I am very new to grafana. Where exactly is my `grafana.ini` located?

**Comment by fabiencharrasse** [comment]
For those who use Grafana in docker, you need to create a grafana.ini file, put [this](https://github.com/stefanprodan/dockprom/issues/294#issuecomment-2005311672) in  and add a volume pointing to the grafana.ini file you just created : 

`- /your/path/to/grafana.ini:/etc/grafana/grafana.ini`

If not using Docker, refer to the [doc](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#configuration-file-location)

**Comment by nightah** [comment]
An alternative is to set the following environment variable:

`GF_FEATURE_TOGGLES_AUTOMIGRATEOLDPANELS=true`

**Comment by ameer1234567890** [comment]
I tried adding the environment variable but it did not work.

According to this [link](https://grafana.com/docs/grafana/latest/developers/angular_deprecation/), the dashboard needs to be manually converted.

**Comment by fabiencharrasse** [comment]
> I tried adding the environment variable but it did not work.
> 
> According to this [link](https://grafana.com/docs/grafana/latest/developers/angular_deprecation/), the dashboard needs to be manually converted.

It didn't work for me either. Try my method with the grafana.ini file

**Comment by ameer1234567890** [comment]
The garafa.ini method worked for me. Thanks
