### ISSUE TITLE
This panel requires Angular (deprecated)

### ISSUE THREAD

**Issue by mdtmailgr** [stefanprodan/dockprom#297]
Dear all,

Thank you very much for using your .DOT files so many years 

I recently updated the used one and I get the  e.g on Docker Containers dashboard 

   ===> This panel requires Angular (deprecated)

Thanks for your feedback 

Best regards,

**Comment by nightah** [comment]
Please refer to: https://github.com/stefanprodan/dockprom/issues/294.

The warnings can safely be ignored for now and when it is deprecated the panels should auto-update.

**Comment by mdtmailgr** [comment]
Thanks you very much for your feedback @nightah !!!!
