### ISSUE TITLE
Big CPU usage while viewing Graphana

### ISSUE THREAD

**Issue by HerkuJIes** [stefanprodan/dockprom#30]
Hi!
When i open any dashboard Graphana in any browser (any OS, any PC and etc.) CPU usage increases to very high values and the browser hangs... How i can solve this problem?
![2017-10-14 21-51-151](https://user-images.githubusercontent.com/13053848/31578540-e0e065ae-b12b-11e7-9478-a8bd647b6bc7.png)

**Comment by lawitschka** [comment]
I am having the same problem. I assume it has something to do with the number of graphs/requests per dashboard. The monitoring services dashboard is working fine, but the Docker containers and host dashboards cause the high load.

Is this a Grafana issue?

**Comment by robboerman** [comment]
Having the same issue. Browser hangs when viewing containers or host dashboards (Chrome, Safari)

**Comment by stefanprodan** [comment]
@HerkuJIes @lawitschka @robboerman can someone please confirm this is fixed in master?

Thanks

**Comment by HerkuJIes** [comment]
I can't confirm this issue... I have a new one, with caddy. So i can't test it. In caddy's log i see: [ERROR 502 /] context canceled. How can i fix this? Google didn't help me with this.

**Comment by stefanprodan** [comment]
@HerkuJIes do a `docker ps -a` I suspect one of the containers is crashing. I did run the stack just now and it works for me on Ubuntu 16.04 with Docker 17.09.

**Comment by HerkuJIes** [comment]
@stefanprodan 
all container's works.
![2017-10-25 20-09-341](https://user-images.githubusercontent.com/13053848/32012694-63f00b3c-b9c1-11e7-93c0-751c1e7fcb83.png)

**Comment by robboerman** [comment]
On OSX the widget with nr of CPU’s crashes the dashboard strangely (on OSX). Next to that I limited the max data points of the graphs a bit. Now everything works

**Comment by lawitschka** [comment]
@stefanprodan Just pulled your recent changes. Using newest Grafana the dashboards are working fine for me
