### ISSUE TITLE
org.label-schema.group does not exist in schema.org

### ISSUE THREAD

**Issue by mvhconsult** [stefanprodan/dockprom#35]
The RC1 of schema.org does not mention this label. Any reason/background to have it in the 1.3 docker-compose.yml?

RC1 version at:  http://label-schema.org/rc1/

**Comment by nightah** [comment]
While it's not in the draft for the schema, it's just a label so I don't think it particularly matters label is used to define the group.
@stefanprodan any feedback on this? Perhaps a quick download as to why you choose this specifically?
