### ISSUE TITLE
Nginx dashboard - no data points

### ISSUE THREAD

**Issue by murbanowicz** [stefanprodan/dockprom#38]
Hi,
First of all thanks for this repo. It's great work and I was looking for something like that long time. Appreciate it!

I have no data points in the Nginx dashboard. Only CPU usage.
Any idea why and what should I do to get the data?

**Comment by morgandenning** [comment]
Do you have an nginx container running?

My understanding is the nginx node was included as an example, however I could be incorrect

**Comment by stefanprodan** [comment]
You need an nginx container and an [nginx exporter](https://github.com/discordianfish/nginx_exporter), once you have that, add the nginx exporter to your Prometheus config.
