### ISSUE TITLE
cAdvisor - Get http://x.x.x.x:8080/metrics: EOF

### ISSUE THREAD

**Issue by jose1660** [stefanprodan/dockprom#39]
Hello team,

I'm trying to monitoring cAdvisor but i get this error message:

![image](https://user-images.githubusercontent.com/1657507/32560181-f589bb64-c476-11e7-8e57-8a57f5489195.png)

Im using this version docker: 

docker-compose version 1.16.1, build 6d1ac21
Docker version 17.03.2-ce, build 7392c3b/17.03.2-ce

I was trying to change some different images of Prometheus but i get the same error.

**Comment by jose1660** [comment]
Im making some test into prometheus container 

![image](https://user-images.githubusercontent.com/1657507/32625176-9113c628-c559-11e7-8ded-57e51b0a112f.png)

**Comment by stefanprodan** [comment]
Looks like a problem with cAdvisor, do you get any errors in cAdvisor logs?

**Comment by jose1660** [comment]
Thank you @stefanprodan i just restart my cAdvisor container and every is Ok

**Comment by vivekj11** [comment]
I know it is closed but I am facing this issue quite often. 
My Cadvisor throws this error and gets restart, during this time (a period of 2-3 minutes) system CPU shoots up to 200%
I doubt this happens due to memory limitations I had applied on my cadvisor container.
Can anyone confirm me here?

my cadvisor config look like- 

    cadvisor:
    image: google/cadvisor:v0.32.0
    networks:
      - monitor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - '--docker_only
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

**Comment by nightah** [comment]
@vivekj11 my instance of cAdvisor is utilising an average of ~223MB of memory I would initially suggest removing the limit and seeing if the issue still persists, if it does please lodge a new ticket with your configuration details and log information and we can investigate.
