### ISSUE TITLE
adding new hosts

### ISSUE THREAD

**Issue by ezeeetm** [stefanprodan/dockprom#4]
This looks great btw, fantastic work and great use of grafana.

re: "all you need to do is to deploy a node-exporter and a cAdvisor container on each host and point the Prometheus server to scrape those"

It's not clear in the docs how to do this. After deploying node-exporter and cAdvisor container on a new host, do we simply add something like this?

```
- job_name: 'nodeexporter'
scrape_interval: 5s
static_configs:
- targets: ['nodeexporter:9100', 'new.host.ip.address:9100']

- job_name: 'cadvisor'
scrape_interval: 5s
static_configs:
- targets: ['cadvisor:8080', 'new.host.ip.address:8080']
```

Or do we need to create new -job_name: entries for each host (with host IP:9100 | 8080 as the targets?

**Comment by stefanprodan** [comment]
Both options should work, I would create new jobs and use the job name to filter the dashboards in case you want to focus just on one host.

**Comment by ismailyenigul** [comment]
I think it will be very good to create a complete prometheus.yml for adding new docker host setup :)
prometheus syntax and workflow is really different at first time for the people used legacy monitoring solutions.
