### ISSUE TITLE
support for Prometheus 2.0?

### ISSUE THREAD

**Issue by explicitcall** [stefanprodan/dockprom#40]
Grafana dashboards supplied by dockprom don't work with Prometheus 2.0

**Comment by Jagostini** [comment]
Have you tested with the last version of Grafana (4.6)?

**Comment by explicitcall** [comment]
Yes, the issue is with prometheus 2.0 removing `count_scalar` function https://www.robustperception.io/functions-to-avoid/

This function is used in dockprom Grafana dashboards: https://github.com/stefanprodan/dockprom/search?utf8=✓&q=count_scalar&type=

**Comment by stefanprodan** [comment]
#42
