### ISSUE TITLE
How to have data written to the local disk

### ISSUE THREAD

**Issue by sundeepk1** [stefanprodan/dockprom#41]
I am trying to get the data written to the local disk so that the data can be retained .

Can you please guide me how to achieve this kind of setup .

I am trying with the below configuration however everytime the container is failing to start if i remove the hash for PROMETHEUS_DATA volume 

services:
  prometheus:
    image: prom/prometheus:v2.0.0
    container_name: Prometheus-Monitoring
    volumes:
      - ./PROMETHEUS:/etc/prometheus/
#      - ./PROMETHEUS_DATA:/etc/prometheus/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/etc/prometheus/data'
      - '--web.enable-lifecycle'
      - '--web.console.templates=consoles'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--storage.tsdb.retention=15d'
      - '--log.level=debug'
      - '--web.enable-admin-api'
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitoring
    labels:
      app: monitoring

**Comment by stefanprodan** [comment]
I'm guessing you're not using dockprom right? dockprom comes with a named docker volume for prometheus ensuring the data will survive container restarts or deletion. You need to explicit delete the volume to erase the data from disk.

**Comment by sundeepk1** [comment]
@stefanprodan I've taken your idea and trying it to work for my use case . 

Say if i am following the named volume as in dockprom, where can i find the data .

**Comment by stefanprodan** [comment]
With `docker volume inspect --format '{{ .Mountpoint }}' prometheus_data ` you will get the exact location on disk
