### ISSUE TITLE
Caddy licensing

### ISSUE THREAD

**Issue by llo94** [stefanprodan/dockprom#44]
Hi,

We would like to use Dockprom for our company internal needs but the Caddy licensing is a no-go.
Is there a way to pull off Caddy from Dockprom ?
Strong authentication is not a need for us because we will only use it inside private networks.

Thanks

**Comment by stefanprodan** [comment]
How is the Caddy licensing a no-go? My Caddy image is Apache 2.0 licensed.

You can remove Caddy and map each service port in the yaml.
