### ISSUE TITLE
Multiple Series Error when getting Free Space

### ISSUE THREAD

**Issue by Steven-Harris** [stefanprodan/dockprom#49]
I am trying to get the free space graph working. I am using btrfs too so I set that entry in the docker_host.json.. I so went and edited the dashboard panel but when I set it to btrfs I get a "Multiple Series Error" because the response I get back from the node_exporter is an array and not a single object.

I am not sure how to filter down to the device I want. Do you have any suggestions?

my current config is just the default
```
(node_filesystem_size{fstype="btrfs"} - node_filesystem_free{fstype="btrfs"}) / node_filesystem_size{fstype="btrfs"}  * 100
```

here is the json it returns.

>[{"datapoints":[[23.06336212158203,1515775249000]],"label":"{device=\"/dev/loop0\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/\"}","id":"{device=\"/dev/loop0\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/\"}","alias":"{device=\"/dev/loop0\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/\"}","stats":{"total":23.06336212158203,"max":23.06336212158203,"min":23.06336212158203,"logmin":23.06336212158203,"avg":23.06336212158203,"current":23.06336212158203,"first":23.06336212158203,"delta":0,"diff":0,"range":0,"timeStep":1.7976931348623157e+308,"count":1},"legend":true,"hasMsResolution":false,"allIsNull":false,"allIsZero":false,"flotpairs":[[1515775249000,23.06336212158203]]},{"datapoints":[[23.06336212158203,1515775249000]],"label":"{device=\"/dev/loop0\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/var/lib/docker\"}","id":"{device=\"/dev/loop0\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/var/lib/docker\"}","alias":"{device=\"/dev/loop0\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/var/lib/docker\"}","stats":{"total":23.06336212158203,"max":23.06336212158203,"min":23.06336212158203,"logmin":23.06336212158203,"avg":23.06336212158203,"current":23.06336212158203,"first":23.06336212158203,"delta":0,"diff":0,"range":0,"timeStep":1.7976931348623157e+308,"count":1},"legend":true,"hasMsResolution":false,"allIsNull":false,"allIsZero":false,"flotpairs":[[1515775249000,23.06336212158203]]},{"datapoints":[[23.06336212158203,1515775249000]],"label":"{device=\"/dev/loop0\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/var/lib/docker/btrfs\"}","id":"{device=\"/dev/loop0\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/var/lib/docker/btrfs\"}","alias":"{device=\"/dev/loop0\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/var/lib/docker/btrfs\"}","stats":{"total":23.06336212158203,"max":23.06336212158203,"min":23.06336212158203,"logmin":23.06336212158203,"avg":23.06336212158203,"current":23.06336212158203,"first":23.06336212158203,"delta":0,"diff":0,"range":0,"timeStep":1.7976931348623157e+308,"count":1},"legend":true,"hasMsResolution":false,"allIsNull":false,"allIsZero":false,"flotpairs":[[1515775249000,23.06336212158203]]},{"datapoints":[[23.06336212158203,1515775249000]],"label":"{device=\"/dev/loop0\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/var/lib/docker/btrfs/subvolumes/b25055e26df1be10643aa21e2963a8955cdd07ebf2a7bcad3465bdfd808a4081\"}","id":"{device=\"/dev/loop0\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/var/lib/docker/btrfs/subvolumes/b25055e26df1be10643aa21e2963a8955cdd07ebf2a7bcad3465bdfd808a4081\"}","alias":"{device=\"/dev/loop0\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/var/lib/docker/btrfs/subvolumes/b25055e26df1be10643aa21e2963a8955cdd07ebf2a7bcad3465bdfd808a4081\"}","stats":{"total":23.06336212158203,"max":23.06336212158203,"min":23.06336212158203,"logmin":23.06336212158203,"avg":23.06336212158203,"current":23.06336212158203,"first":23.06336212158203,"delta":0,"diff":0,"range":0,"timeStep":1.7976931348623157e+308,"count":1},"legend":true,"hasMsResolution":false,"allIsNull":false,"allIsZero":false,"flotpairs":[[1515775249000,23.06336212158203]]},{"datapoints":[[87.30685779913249,1515775249000]],"label":"{device=\"/dev/md1\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/mnt/disk1\"}","id":"{device=\"/dev/md1\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/mnt/disk1\"}","alias":"{device=\"/dev/md1\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/mnt/disk1\"}","stats":{"total":87.30685779913249,"max":87.30685779913249,"min":87.30685779913249,"logmin":87.30685779913249,"avg":87.30685779913249,"current":87.30685779913249,"first":87.30685779913249,"delta":0,"diff":0,"range":0,"timeStep":1.7976931348623157e+308,"count":1},"legend":true,"hasMsResolution":false,"allIsNull":false,"allIsZero":false,"flotpairs":[[1515775249000,87.30685779913249]]},{"datapoints":[[87.71065207811158,1515775249000]],"label":"{device=\"/dev/md2\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/mnt/disk2\"}","id":"{device=\"/dev/md2\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/mnt/disk2\"}","alias":"{device=\"/dev/md2\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/mnt/disk2\"}","stats":{"total":87.71065207811158,"max":87.71065207811158,"min":87.71065207811158,"logmin":87.71065207811158,"avg":87.71065207811158,"current":87.71065207811158,"first":87.71065207811158,"delta":0,"diff":0,"range":0,"timeStep":1.7976931348623157e+308,"count":1},"legend":true,"hasMsResolution":false,"allIsNull":false,"allIsZero":false,"flotpairs":[[1515775249000,87.71065207811158]]},{"datapoints":[[86.93418322690847,1515775249000]],"label":"{device=\"/dev/md3\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/mnt/disk3\"}","id":"{device=\"/dev/md3\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/mnt/disk3\"}","alias":"{device=\"/dev/md3\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/mnt/disk3\"}","stats":{"total":86.93418322690847,"max":86.93418322690847,"min":86.93418322690847,"logmin":86.93418322690847,"avg":86.93418322690847,"current":86.93418322690847,"first":86.93418322690847,"delta":0,"diff":0,"range":0,"timeStep":1.7976931348623157e+308,"count":1},"legend":true,"hasMsResolution":false,"allIsNull":false,"allIsZero":false,"flotpairs":[[1515775249000,86.93418322690847]]},{"datapoints":[[86.96944050202295,1515775249000]],"label":"{device=\"/dev/md4\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/mnt/disk4\"}","id":"{device=\"/dev/md4\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/mnt/disk4\"}","alias":"{device=\"/dev/md4\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/mnt/disk4\"}","stats":{"total":86.96944050202295,"max":86.96944050202295,"min":86.96944050202295,"logmin":86.96944050202295,"avg":86.96944050202295,"current":86.96944050202295,"first":86.96944050202295,"delta":0,"diff":0,"range":0,"timeStep":1.7976931348623157e+308,"count":1},"legend":true,"hasMsResolution":false,"allIsNull":false,"allIsZero":false,"flotpairs":[[1515775249000,86.96944050202295]]},{"datapoints":[[48.815854517282645,1515775249000]],"label":"{device=\"/dev/sdf1\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/mnt/cache\"}","id":"{device=\"/dev/sdf1\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/mnt/cache\"}","alias":"{device=\"/dev/sdf1\",fstype=\"btrfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/rootfs/mnt/cache\"}","stats":{"total":48.815854517282645,"max":48.815854517282645,"min":48.815854517282645,"logmin":48.815854517282645,"avg":48.815854517282645,"current":48.815854517282645,"first":48.815854517282645,"delta":0,"diff":0,"range":0,"timeStep":1.7976931348623157e+308,"count":1},"legend":true,"hasMsResolution":false,"allIsNull":false,"allIsZero":false,"flotpairs":[[1515775249000,48.815854517282645]]}]

**Comment by nightah** [comment]
I had a similar problem with zfs, I amended the query to select based on fstype and mountpoint like such:
```
(node_filesystem_size{fstype="btrfs",mountpoint="/mountpointhere/} - node_filesystem_free{fstype="btrfs",mountpoint="/mountpointhere/}) / node_filesystem_size{fstype="btrfs",mountpoint="/mountpointhere/}  * 100
```
There likely is a much better way to handle this too.

**Comment by Steven-Harris** [comment]
What worked perfectly thanks @nightah
