### ISSUE TITLE
alertmanager exited with code 1

### ISSUE THREAD

**Issue by dbachko** [stefanprodan/dockprom#50]
<img width="602" alt="screen shot 2018-01-16 at 12 39 37 pm" src="https://user-images.githubusercontent.com/9260214/35003473-f60d2402-faba-11e7-9227-e9b43af28351.png">

**Comment by stefanprodan** [comment]
This is due to the fact that Alertmanager switched to kingpin https://github.com/prometheus/alertmanager/commit/b7da058efbd1a13cfc56b58f6572687e7da6d6ed
