### ISSUE TITLE
machine_cpu_cores -> sum(machine_cpu_cores) ?

### ISSUE THREAD

**Issue by ScottBrenner** [stefanprodan/dockprom#56]
https://github.com/stefanprodan/dockprom/blob/3483e5ed08d6df273522492e7b99a8b46ec63475/grafana/dashboards/docker_containers.json#L160

Shouldn't this be `sum(machine_cpu_cores)`? Otherwise I'm seeing a `Multiple Series Error` when monitoring across multiple hosts. Believe several other metrics could use this change as well.

**Comment by stefanprodan** [comment]
The current dashboards and working for a single host only. If you care to adapt them for multi-host please make a PR.

Thanks
