### ISSUE TITLE
The same issue in your technology stack between prometheus and alertmanager

### ISSUE THREAD

**Issue by vovkanaz** [stefanprodan/dockprom#59]
Hello, here you can see error trace
{"status":"error","errorType":"bad_data","error":"start time must be before end time"}
As i understood from https://github.com/prometheus/prometheus/issues/3543
This issue between Prometheus: 2.1.0 & Alertmanager: 0.13.0, actually prometheus send invalid data to alertmanager and it can't processed them. So what should we do for resolve this trouble, may be wait for new Prometheus 2.2 and Alertmanager 0.14, or how we can downgrade to Prometheus 2.0(it's resolve this issue) based on Docker Compose.
Thanks a lot for your work, you project is amazing!
P.S . In Alertmanager 0.14 Release Notes i see  [BUGFIX] Don't count alerts with EndTime in the future as resolved

**Comment by stefanprodan** [comment]
Can you please try `prometheus:v2.2.0-rc.0` and see if that works? If so a PR would be great.

Thanks

**Comment by vovkanaz** [comment]
Yes, sure I'll give you feedback :)

**Comment by vovkanaz** [comment]
@stefanprodan With prometheus:v2.2.0-rc.0 all working as well. Thank you!
