### ISSUE TITLE
Service monitoring not working

### ISSUE THREAD

**Issue by gillesbroes2016** [stefanprodan/dockprom#60]
When I try to monitor an application, for example Redis, I'm having issues.
My config:

*docker-compose.yml:
-------------

prometheus:
    image: stefanprodan/swarmprom-prometheus
    environment:
      - JOBS=redis-exporter:9121

*prometheus.yml:
-------------

  - job_name: 'redis-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.redis-exporter'
      type: 'A'
      port: 9121

*compose-redis.yml:
-------------

version: '3'

networks:
  mon_net:
    external: true

services:
  redis:
    image: redis
    networks:
      - mon_net
    ports:
      - "6379:6379"
    deploy:
      mode: global
     
  redis-exporter:
    image: oliver006/redis_exporter
    networks:
      - mon_net
    ports:
      - "9121:9121"
    deploy:
      mode: global

When I run the monitoring stack and then compose-redis:

Prometheus goes up and down all the time.

Log shows:

level=error ts=2018-02-19T16:49:15.594740858Z caller=main.go:582 err="Error loading config couldn't load configuration (--config.file=/etc/prometheus/prometheus.yml): parsing YAML file /etc/prometheus/prometheus.yml: unknown fields in alertmanager config: job_name"

I have no idea how to fix this or what I did wrong.
Any help would be appreciated.

Thanks

**Comment by stefanprodan** [comment]
You are using the `swarmprom` image with this setup??

**Comment by gillesbroes2016** [comment]
Yes, I'm using the stefanprodan/swarmprom-prometheus image.

I followed the instructions, first everything works. (default dashboards).

After making the changes that I listed above, promotheus stops running.

Running docker container logs mon_prometheus I see the error above.

**Comment by stefanprodan** [comment]
If you using swarmprom why is this issue in the dockprom repo?

**Comment by gillesbroes2016** [comment]
I'm sorry, I missed.
