### ISSUE TITLE
need root privilege to run prometheus

### ISSUE THREAD

**Issue by DeoLeung** [stefanprodan/dockprom#66]
https://github.com/stefanprodan/dockprom/blob/master/docker-compose.yml#L15

I had to add
```Dockerfile
prometheus:
  user: root
  privileged: true
```
to make it work, maybe someone else needs this information

**Comment by jonathan599** [comment]
thanks for the update :)

**Comment by willhallonline** [comment]
Just as a note, I had to do this too.

**Comment by nightah** [comment]
@DeoLeung and @willhallonline this should not be required unless permissions for your respective files have changed. Can you confirm the permissions of your prometheus_data volume?
