### ISSUE TITLE
Can't authenticate in Grafana

### ISSUE THREAD

**Issue by fazuw** [stefanprodan/dockprom#68]
Hi,

I tried to install dockprom but i can't login in grafana. 
The config is not changed at all. 
I just ran ` sudo ADMIN_USER=admin ADMIN_PASSWORD=admin docker-compose up`

![image](https://user-images.githubusercontent.com/12171004/37411588-6c37972e-27a3-11e8-9d36-a97f544a3515.png)

**Comment by sebthemonster** [comment]
Hi,
Do you try from a browser ?

**Comment by jonathan599** [comment]
i tried from browser and i get this

standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"

please can you assist
