### ISSUE TITLE
Update image versions

### ISSUE THREAD

**Issue by pSchaub** [stefanprodan/dockprom#69]
I see that the versions of the images in `docker-compose.yml` are not the latest versions.
Please update to the latest versions.

**Comment by sidewinder12s** [comment]
Looks like some of these images probably require configuration updates, especially Grafana to update to the latest versions.

I did update prom to the latest and it seems to be working fine, though I haven't done any extensive testing other than checking if grafana still is updating.

**Comment by pascalandy** [comment]
@pSchaub have you tried to update the image and see how the system behave?

> Please update to the latest versions.
