### ISSUE TITLE
Add 'unsee' alert dashboard

### ISSUE THREAD

**Issue by pschaub** [stefanprodan/dockprom#70]
I think it would be very nice to add `unsee` to this repo.
See: https://github.com/cloudflare/unsee

**Comment by hlovdal** [comment]
That repository has been archived and has not had any releases or updates in three years, so I highly doubt that it makes sense any longer to add it.

**Comment by pschaub** [comment]
When I wrote this issue, the project seemed to be still active. I agree with you, now it doesn't make sense anymore. Closed.
