### ISSUE TITLE
unknown function with name "count_scalar"

### ISSUE THREAD

**Issue by loxon-lab** [stefanprodan/dockprom#72]
Hello,

Thanks your work, I tried it, and I got the following error in CPU graph panel, and "Running container" panel in "Docker Containers" dashboard:

```
{
  "status": "error",
  "errorType": "bad_data",
  "error": "parse error at char 134: unknown function with name \"count_scalar\"",
  "message": "parse error at char 134: unknown function with name \"count_scalar\""
}
```

Can u help me about this bug?

I tried it today (2018-03-26 5pm), and follow the README.md description.

```
git clone https://github.com/stefanprodan/dockprom
cd dockprom
ADMIN_USER=admin ADMIN_PASSWORD=admin docker-compose up -d
```

Thanks

**Comment by stefanprodan** [comment]
That's strange, there is no `count_scalar` in here https://github.com/stefanprodan/dockprom/blob/master/grafana/dashboards/docker_containers.json

When upgrading the project to Prometheus v2 I've replaced count_scalar with count everywhere.

**Comment by loxon-lab** [comment]
Yes, in my workspace also there is no count_scalar, but when the container start, there is.

Maybe the docker image:prom/prometheus:v2.2.0-rc.0 contains something like this ...

**Comment by loxon-lab** [comment]
Yes, if I use the latest grafana image, then it works well, lease upgrade to the latest image :)
