### ISSUE TITLE
Filter by docker service label

### ISSUE THREAD

**Issue by kiddo3** [stefanprodan/dockprom#75]
Hello,
I'm using the docker swarm monitor services dashboard and is really useful. I'm wondering if there is any way to  add a filter to the dashboard, based on docker services labels, to filter and only show the services wich contains label="xxx".

**Comment by thomasleveil** [comment]
take a look at https://github.com/thomasleveil/dockprom/commit/2802e98022fdf56e9852ba32029f96c487d866bc

**Comment by nightah** [comment]
@kiddo3 please lodge an issue over at https://github.com/stefanprodan/swarmprom/ as that's the correct repo for the swarm varaint. If alternatively you are looking to utilise dockprom with this, the commit @thomasleveil has referenced above is a good example.
