### ISSUE TITLE
Redirect loclhost:3000 to 80

### ISSUE THREAD

**Issue by Dante3004** [stefanprodan/dockprom#77]
Hi, i really like your job and i hope you can help me (sorry i'm noobie)
How can i redirect default port of web interface to 80 ? (443 eventually)

Thanks in advance for helping :)

**Comment by pascalandy** [comment]
I guess you refer to redirect the port of the GUI Grafana right?
See https://github.com/stefanprodan/dockprom/blob/master/docker-compose.yml#L103

**Comment by Dante3004** [comment]
Thank you for your answer.
I just realized that I was wrong, the request is for a swarm environment. 
I'm gonna open an new issue in the right repos

**Comment by pascalandy** [comment]
You're welcome!
