### ISSUE TITLE
Readme issues

### ISSUE THREAD

**Issue by jwillmer** [stefanprodan/dockprom#82]
The following links are not working:

> I've setup three alerts configuration files:
> 
> Monitoring services alerts **targets.rules**
> Docker Host alerts **host.rules**
> Docker Containers **alerts containers.rules**

There are specified rules for Jenkins but Jenkins is not part of the installation. Is this only to show how failed alerts will look like? Maybe a comment about this would be nice in the Readme.

**Comment by nightah** [comment]
You are absolutely correct in regards to the file reference issue in the `README.md` I'm about to correct that. 

Regarding the alert groups, they are intended to be used as examples.

Most people nowadays have multicore CPUs so they would want to change the node_load1 value from `1.5` to something more appropriate to the hardware they are running.
Likewise can be said for the Jenkins container example, you should adjust these in accordance with whatever alerts you would like to receive.
