### ISSUE TITLE
Graphana container keeps restarting

### ISSUE THREAD

**Issue by jonathan599** [stefanprodan/dockprom#85]
I tried to install dockprom but grafana doesn't come up.The config is not changed at all.

In browser i get this issue : 502 Bad Gateway

and docker container logs are:

standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"

**Comment by jonathan599** [comment]
still problm exists

**Comment by Yivan** [comment]
Hi! Maybe this issue can resolve your problem: https://github.com/stefanprodan/dockprom/issues/87

**Comment by adelcourt** [comment]
i have the same problem  and resolved by chmod +x on setup.sh

**Comment by nightah** [comment]
The `setup.sh` has been pushed to the repo with the appropriate permissions so that means when you initially clone the repo it should have the executable bit `+x` inherently.
@jonathan599 can you confirm if this has been resolved for you, if not please open another issue with the respective logs and we can address this.
