### ISSUE TITLE
On Windows .gitattribute make clone with CRLF instead LF.

### ISSUE THREAD

**Issue by Yivan** [stefanprodan/dockprom#87]
Hello!

Thanks for sharing this nice project.

I just cloned the project (Windows 10), and i got error with Grafana:

```
> docker logs grafana
standard_init_linux.go:190: exec user process caused "no such file or directory"
```

I found that the files have been all cloned with CRLF end of lines. This is du to the .gitattribute files I think ("text=auto"). You should remove this file at all i think.
By modifying the grafana/setup.sh file with good linux (LF) EOL, all is ok.

**Comment by Yivan** [comment]
Hi, any news on this issue please ?

**Comment by nightah** [comment]
@Yivan I don't actually have a windows machine to test this, though I understand you can also change this client side based on your [core.autocrlf](https://help.github.com/articles/dealing-with-line-endings/) setting.

I'll fix up the `.gitattribute` on another branch tonight, if you don't mind testing and then I can push changes for the `.gitattribute` back to master.

**Comment by nightah** [comment]
@Yivan could you try the `fix-line-endings` branch and report back your results please?
`git clone https://github.com/stefanprodan/dockprom.git --branch fix-line-endings`

**Comment by Yivan** [comment]
Hello !
Thanks for your return.
I juste tested it (last Docker for Windows version) and there is no more problem with this new branch, great.
So the problem is resolved with this new branch.

I would like to add that on Windows for Docker the rootfs is "/c" and not "/", so i had to change manually in docker-compose.yml file `/:/rootfs:ro` by `/c:/rootfs:ro`, after that the up went well and i can login in GUI interfaces.
Maby it could be added in the installation step for Windows users.

Thanks.
