### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by nicolas-mosch** [stefanprodan/dockprom#88]
I have been trying to set it up so that Grafana uses an https connection without success. Is there a way of doing this?

**Comment by sebthemonster** [comment]
I success to do this with nginx and let's encrypt. I write a simple virtualhost what proxies request to localhost:3000.

**Comment by sachk** [comment]
You can modify the Caddyfile included with the domain you're using as such

`
sub.domain.com {
    basicauth / {$ADMIN_USER} {$ADMIN_PASSWORD}
    proxy / prometheus:9090 {
            transparent
        }

    errors stderr
}
`

However, let's encrypt only works on port 80/443 for verification so you can't keep the ports the same

**Comment by nightah** [comment]
@nicolas-mosch, as per the other comments your best bet is to put the either Grafana itself or the caddy instance behind a reverse proxy which is secured.

**Comment by gowrisankar22** [comment]
@sachk @nightah I dont want certificates , but just open via dns instead ip:port. What should  have to do ?
