### ISSUE TITLE
Grafana setup script error

### ISSUE THREAD

**Issue by OvidiuTa** [stefanprodan/dockprom#94]
Hello,
I tried to deploy the env via docker compose and I get an error on Grafana side. These are the logs when I run the setup script inside the container.
Can anyone please gice some advice? 

Running curl -L -s --fail -H "Accept: application/json" -H "Content-Type: application/json" -X POST -k http://admin:admin@localhost:3000/api/datasources --data @/etc/grafana/datasources/Prometheus.json
INFO[08-23|20:59:09] Initializing InternalMetricsService      logger=server
INFO[08-23|20:59:09] Initializing AlertingService             logger=server
INFO[08-23|20:59:09] Initializing HTTPServer                  logger=server
INFO[08-23|20:59:09] Initializing CleanUpService              logger=server
INFO[08-23|20:59:09] Initializing NotificationService         logger=server
INFO[08-23|20:59:09] Initializing ProvisioningService         logger=server
INFO[08-23|20:59:09] Initializing RenderingService            logger=server
INFO[08-23|20:59:09] Initializing TracingService              logger=server
INFO[08-23|20:59:09] Initializing Stream Manager
INFO[08-23|20:59:09] HTTP Server Listen                       logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
EROR[08-23|20:59:09] Stopped HTTPServer                       logger=server reason="listen tcp 0.0.0.0:3000: bind: address already in use"
INFO[08-23|20:59:09] Stopped AlertingService                  logger=server reason="context canceled"
INFO[08-23|20:59:09] Stopped Stream Manager
INFO[08-23|20:59:09] Stopped InternalMetricsService           logger=server reason="context canceled"
install failed
Installing dashboard /etc/grafana/dashboards/docker_containers.json
./setup.sh: line 63: /etc/grafana/dashboards/docker_containers.json.wrapped: Permission denied
Running curl -L -s --fail -H "Accept: application/json" -H "Content-Type: application/json" -X POST -k http://admin:admin@localhost:3000/api/dashboards/db --data @/etc/grafana/dashboards/docker_containers.json.wrapped
install failed
rm: cannot remove '/etc/grafana/dashboards/docker_containers.json.wrapped': No such file or directory
Installing dashboard /etc/grafana/dashboards/docker_host.json
./setup.sh: line 63: /etc/grafana/dashboards/docker_host.json.wrapped: Permission denied
Running curl -L -s --fail -H "Accept: application/json" -H "Content-Type: application/json" -X POST -k http://admin:admin@localhost:3000/api/dashboards/db --data @/etc/grafana/dashboards/docker_host.json.wrapped
install failed
rm: cannot remove '/etc/grafana/dashboards/docker_host.json.wrapped': No such file or directory
Installing dashboard /etc/grafana/dashboards/monitor_services.json
./setup.sh: line 63: /etc/grafana/dashboards/monitor_services.json.wrapped: Permission denied
Running curl -L -s --fail -H "Accept: application/json" -H "Content-Type: application/json" -X POST -k http://admin:admin@localhost:3000/api/dashboards/db --data @/etc/grafana/dashboards/monitor_services.json.wrapped
install failed
rm: cannot remove '/etc/grafana/dashboards/monitor_services.json.wrapped': No such file or directory
Installing dashboard /etc/grafana/dashboards/nginx_container.json
./setup.sh: line 63: /etc/grafana/dashboards/nginx_container.json.wrapped: Permission denied
Running curl -L -s --fail -H "Accept: application/json" -H "Content-Type: application/json" -X POST -k http://admin:admin@localhost:3000/api/dashboards/db --data @/etc/grafana/dashboards/nginx_container.json.wrapped
install failed
rm: cannot remove '/etc/grafana/dashboards/nginx_container.json.wrapped': No such file or directory
INFO[08-23|20:59:09] Stopped PluginManager                    logger=server reason="context canceled"
EROR[08-23|20:59:09] Server shutdown                          logger=server reason="listen tcp 0.0.0.0:3000: bind: address already in use"

**Comment by smiller393** [comment]
+1 Getting the same issue when running this on a new server

**Comment by nightah** [comment]
You shouldn't have to run this as root to fix the problem.
The permission problem on initial dashboard creation had to do with folder permissions and how the dashboards were being loaded via the setup.sh script.

#97 resolves this issue.
