### ISSUE TITLE
Monitoring remote host..

### ISSUE THREAD

**Issue by kkalugerov** [stefanprodan/dockprom#95]
Hello @stefanprodan , 
I would like to ask you if there is a way with this stack to monitor a remote host :? For example if I use this stack on one machine can I monitor an other one with different address :? If yes, is it possible to explain how :?

**Comment by kkalugerov** [comment]
Manage to resolve it.

**Comment by apsharma** [comment]
@kkalugerov : Could you please briefly explain how were you able to resolve this ? I am looking to do the same thing : Setup dockprom on one machine and monitor a remote Docker Host running all the containers/services.
