### ISSUE TITLE
Cannot import the dashboards

### ISSUE THREAD

**Issue by wichtounet** [stefanprodan/dockprom#98]
Hi, 

Thanks a lot for this great repository :)

I have added the data source into Grafana, it seems to work. Prometheus and cadvisor seem to be working as well. 

However, I am having a hard time importing the graphs. There are not imported directly. And if I try to import them by copying the JSON into the GUI, I get an empty dashboard (not even empty graphs, just empty page, no panels). 

Is there something specific to do to import the dashboards? 

Thanks

**Comment by wichtounet** [comment]
I found how to import them manually :)

Just need to change the first line and the last line of the JSON file :)

**Comment by TachyonRSA** [comment]
> I found how to import them manually :)
> 
> Just need to change the first line and the last line of the JSON file :)

What did you need to change on the first and last line @wichtounet ?

**Comment by bascouba** [comment]
I just figured it out. Remove the `{"dashboard":` and the last bracket  `}`
